/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all projects */
        get: operations["listProjects"];
        put?: never;
        /** Create a new project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** Get project by ID */
        get: operations["getProject"];
        /** Update project */
        put: operations["updateProject"];
        post?: never;
        /** Delete project */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** Get project statistics */
        get: operations["getProjectStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/issues": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** List issues in project */
        get: operations["listIssues"];
        put?: never;
        /** Create a new issue */
        post: operations["createIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{issueId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        /**
         * Get issue by globally-unique ID
         * @description Retrieves an issue by its globally-unique ID without requiring project context. Use this endpoint when you have an issue ID but don't know or need the project.
         */
        get: operations["getIssueByID"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/issues/{issueId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        /**
         * Get issue by ID within a project
         * @description Retrieves an issue by ID within a project-scoped route. Validates the issue belongs to the specified project.
         */
        get: operations["getIssue"];
        /** Update issue */
        put: operations["updateIssue"];
        post?: never;
        /** Delete issue */
        delete: operations["deleteIssue"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/issues/{issueId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close an issue */
        post: operations["closeIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/issues/{issueId}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen a closed issue */
        post: operations["reopenIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/ready": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** Get issues ready to work on (no blocking dependencies) */
        get: operations["getReadyWork"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/blocked": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /** Get blocked issues */
        get: operations["getBlockedIssues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/team-context": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        /**
         * Get issues grouped by teammate role labels
         * @description Returns issues grouped by their `teammate:*` labels. When an epic_id is
         *     provided, only children of that epic (via parent-child dependency) are
         *     included. Without epic_id, all non-closed issues with teammate labels
         *     in the project are returned.
         */
        get: operations["getTeamContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List AI sessions */
        get: operations["listAISessions"];
        put?: never;
        /** Create a new AI session */
        post: operations["createAISession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description AI session ID */
                sessionId: string;
            };
            cookie?: never;
        };
        /** Get AI session by ID */
        get: operations["getAISession"];
        put?: never;
        post?: never;
        /** Delete AI session */
        delete: operations["deleteAISession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/sessions/{sessionId}/agents": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description AI session ID */
                sessionId: string;
            };
            cookie?: never;
        };
        /** List AI agents for a session */
        get: operations["listAIAgents"];
        put?: never;
        /** Create a new AI agent */
        post: operations["createAIAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/sessions/{sessionId}/agents/{agentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description AI session ID */
                sessionId: string;
                /** @description AI agent ID */
                agentId: string;
            };
            cookie?: never;
        };
        /** Get AI agent by ID */
        get: operations["getAIAgent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/issues/{issueId}/deps": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        /** Get issue dependencies and dependents */
        get: operations["getDependencies"];
        put?: never;
        /** Add a dependency to an issue */
        post: operations["addDependency"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/issues/{issueId}/deps/{dependsOnId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
                /** @description ID of the dependency to remove */
                dependsOnId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a dependency from an issue */
        delete: operations["removeDependency"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all global labels */
        get: operations["listLabels"];
        put?: never;
        /** Create a new label */
        post: operations["createLabel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labels/{labelName}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Label name */
                labelName: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Update a label */
        put: operations["updateLabel"];
        post?: never;
        /** Delete a label */
        delete: operations["deleteLabel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/issues/{issueId}/labels": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a label to an issue */
        post: operations["addLabelToIssue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/issues/{issueId}/labels/{labelName}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
                /** @description Label name to remove */
                labelName: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a label from an issue */
        delete: operations["removeLabelFromIssue"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/issues/{issueId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        /** Get comments for an issue */
        get: operations["getComments"];
        put?: never;
        /** Add a comment to an issue */
        post: operations["addComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/issues/{issueId}/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
                /** @description Comment ID */
                commentId: number;
            };
            cookie?: never;
        };
        get?: never;
        /** Update a comment */
        put: operations["updateComment"];
        post?: never;
        /** Delete a comment */
        delete: operations["deleteComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectId}/issues/{issueId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        /** Get audit events for an issue */
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register an ephemeral plan */
        post: operations["createPlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{planId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        /** Get plan metadata and file content */
        get: operations["getPlan"];
        /** Update plan file content */
        put: operations["updatePlanContent"];
        post?: never;
        /** Delete plan and its comments */
        delete: operations["deletePlan"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{planId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update plan status */
        patch: operations["updatePlanStatus"];
        trace?: never;
    };
    "/plans/{planId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        /** List plan review comments */
        get: operations["listPlanComments"];
        put?: never;
        /** Add a review comment */
        post: operations["createPlanComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Error message */
            error: string;
        };
        /** @enum {string} */
        Status: "open" | "in_progress" | "blocked" | "deferred" | "closed";
        /** @enum {string} */
        IssueType: "bug" | "feature" | "task" | "epic" | "chore";
        /** @enum {string} */
        DependencyType: "blocks" | "parent-child" | "related" | "discovered-from";
        /** @enum {string} */
        EventType: "created" | "updated" | "status_changed" | "commented" | "closed" | "reopened" | "dependency_added" | "dependency_removed" | "label_added" | "label_removed";
        Project: {
            /** @description Unique project ID (e.g., "proj-a1b2") */
            id: string;
            /** @description Display name */
            name: string;
            /** @description Optional associated directory path */
            path?: string;
            /** @description Project description */
            description?: string;
            /** @description Issue ID prefix (e.g., "bd") */
            prefix: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateProjectRequest: {
            /** @description Display name */
            name: string;
            /** @description Optional associated directory path */
            path?: string;
            /** @description Project description */
            description?: string;
            /** @description Issue ID prefix */
            prefix: string;
        };
        UpdateProjectRequest: {
            /** @description New display name */
            name?: string;
            /** @description New associated directory path */
            path?: string;
            /** @description New description */
            description?: string;
        };
        Statistics: {
            project_id: string;
            total_issues: number;
            open_issues: number;
            in_progress_issues: number;
            closed_issues: number;
            blocked_issues: number;
            deferred_issues: number;
            ready_issues: number;
            /** Format: double */
            avg_lead_time_hours?: number;
        };
        Issue: {
            /** @description Unique issue ID */
            id: string;
            project_id: string;
            title: string;
            description?: string;
            status: components["schemas"]["Status"];
            /** @description 0 (critical) - 4 (backlog) */
            priority: number;
            /** @description 0 = unranked (sorts last), 1+ = lower rank = work on first */
            rank?: number;
            issue_type: components["schemas"]["IssueType"];
            /** @description AI coding session UUID (e.g., Claude Code session ID) */
            ai_session_id?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            closed_at?: string;
            close_reason?: string;
            /** @description External reference (e.g., "gh-9", "jira-ABC") */
            external_ref?: string;
            labels?: string[];
            dependencies?: components["schemas"]["Dependency"][];
            comments?: components["schemas"]["Comment"][];
        };
        IssueDetails: components["schemas"]["Issue"] & {
            dependents?: components["schemas"]["Dependency"][];
        };
        BlockedIssue: components["schemas"]["Issue"] & {
            blocked_by_count: number;
            blocked_by: string[];
        };
        PaginatedIssues: {
            data: components["schemas"]["Issue"][];
            total?: number;
            limit?: number;
            offset?: number;
        };
        PaginatedAISessions: {
            data: components["schemas"]["AISessionResponse"][];
            total?: number;
            limit?: number;
            offset?: number;
        };
        TeamContext: {
            /** @description Project ID */
            project: string;
            epic?: components["schemas"]["TeamContextEpic"];
            /** @description Issues grouped by teammate role name */
            roles: {
                [key: string]: components["schemas"]["TeamContextRole"];
            };
        };
        TeamContextEpic: {
            id: string;
            title: string;
        };
        TeamContextRole: {
            issues: components["schemas"]["TeamContextIssue"][];
        };
        TeamContextIssue: {
            id: string;
            title: string;
            priority: number;
            status: string;
            type: string;
            /** @description IDs of issues this depends on */
            deps?: string[];
        };
        CreateIssueRequest: {
            title: string;
            description?: string;
            status?: components["schemas"]["Status"];
            /** @default 2 */
            priority: number;
            issue_type?: components["schemas"]["IssueType"];
            /** @description AI coding session UUID */
            ai_session_id?: string;
            external_ref?: string;
        };
        UpdateIssueRequest: {
            title?: string;
            description?: string;
            status?: components["schemas"]["Status"];
            priority?: number;
            issue_type?: components["schemas"]["IssueType"];
            /** @description AI coding session UUID */
            ai_session_id?: string;
            external_ref?: string;
        };
        CloseIssueRequest: {
            /** @description Reason for closing */
            reason?: string;
        };
        Dependency: {
            issue_id: string;
            depends_on_id: string;
            type: components["schemas"]["DependencyType"];
            /** Format: date-time */
            created_at: string;
            created_by?: string;
        };
        DependencyGraph: {
            dependencies: components["schemas"]["Dependency"][];
            dependents: components["schemas"]["Dependency"][];
        };
        AddDependencyRequest: {
            /** @description ID of the issue this depends on */
            depends_on_id: string;
            type: components["schemas"]["DependencyType"];
        };
        Label: {
            name: string;
            /** @description Hex color code (e.g., "#ff0000") */
            color?: string;
            description?: string;
        };
        CreateLabelRequest: {
            name: string;
            color?: string;
            description?: string;
        };
        UpdateLabelRequest: {
            color?: string;
            description?: string;
        };
        AddLabelToIssueRequest: {
            label: string;
        };
        Comment: {
            /** Format: int64 */
            id: number;
            issue_id: string;
            author: string;
            text: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        AddCommentRequest: {
            text: string;
        };
        UpdateCommentRequest: {
            text: string;
        };
        Event: {
            /** Format: int64 */
            id: number;
            issue_id: string;
            event_type: components["schemas"]["EventType"];
            actor: string;
            old_value?: string;
            new_value?: string;
            comment?: string;
            /** Format: date-time */
            created_at: string;
        };
        AISessionResponse: {
            /** @description Unique AI session ID */
            id: string;
            /** @description Path to the session transcript file */
            transcript_path: string;
            /** @description Working directory for the session */
            cwd?: string;
            /** Format: date-time */
            started_at: string;
        };
        CreateAISessionRequest: {
            /** @description AI session ID */
            id: string;
            /** @description Path to the session transcript file */
            transcript_path: string;
            /** @description Working directory for the session */
            cwd?: string;
            /**
             * Format: date-time
             * @description Session start time (defaults to current time)
             */
            started_at?: string;
        };
        AIAgentResponse: {
            /** @description Unique AI agent ID */
            id: string;
            /** @description Parent session ID */
            session_id: string;
            /** @description Agent task description */
            description?: string;
            /** @description Agent prompt text */
            prompt?: string;
            /** @description Type of agent (e.g., "task", "code") */
            agent_type?: string;
            /** @description AI model used */
            model?: string;
            /** @description Agent status (running, completed, error) */
            status: string;
            /** @description Duration in milliseconds */
            duration_ms?: number;
            /** @description Total tokens consumed */
            total_tokens?: number;
            /** @description Number of tool uses */
            tool_use_count?: number;
            /** Format: date-time */
            created_at: string;
        };
        CreateAIAgentRequest: {
            /** @description AI agent ID */
            id: string;
            /** @description Parent session ID */
            session_id: string;
            /** @description Agent task description */
            description?: string;
            /** @description Agent prompt text */
            prompt?: string;
            /** @description Type of agent */
            agent_type?: string;
            /** @description AI model used */
            model?: string;
            /** @description Agent status (defaults to "running") */
            status?: string;
        };
        /** @enum {string} */
        PlanStatus: "draft" | "in_review" | "approved" | "rejected";
        Plan: {
            /** @description Unique plan ID (plan.xxxxx format) */
            id: string;
            /** @description Relative path to the plan markdown file */
            file_path: string;
            status: components["schemas"]["PlanStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PlanWithContent: components["schemas"]["Plan"] & {
            /** @description Markdown content read from the plan file */
            content?: string;
        };
        PlanComment: {
            id: string;
            plan_id: string;
            /** @description Line number anchor (null for overall feedback) */
            line_number?: number | null;
            content: string;
            /** Format: date-time */
            created_at: string;
        };
        CreatePlanRequest: {
            file_path: string;
        };
        UpdatePlanContentRequest: {
            content: string;
        };
        UpdatePlanStatusRequest: {
            status: components["schemas"]["PlanStatus"];
        };
        CreatePlanCommentRequest: {
            line_number?: number | null;
            content: string;
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Project ID */
        ProjectId: string;
        /** @description Issue ID */
        IssueId: string;
        /** @description User performing the action (defaults to "anonymous") */
        ActorHeader: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Project created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description Project updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getProjectStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Statistics"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listIssues: {
        parameters: {
            query?: {
                /** @description Filter by status (supports multiple values) */
                status?: components["schemas"]["Status"][];
                /** @description Filter by issue type (supports multiple values) */
                type?: components["schemas"]["IssueType"][];
                /** @description Filter by priority (supports multiple values, 0-4) */
                priority?: number[];
                /** @description Filter by AI session ID */
                ai_session_id?: string;
                /** @description Filter by parent issue ID (returns children via parent-child dependency) */
                parent_id?: string;
                /** @description Full-text search query */
                q?: string;
                /** @description Maximum results to return */
                limit?: number;
                /** @description Pagination offset */
                offset?: number;
            };
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of issues */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedIssues"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createIssue: {
        parameters: {
            query?: never;
            header?: {
                /** @description User performing the action (defaults to "anonymous") */
                "X-Actor"?: components["parameters"]["ActorHeader"];
            };
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIssueRequest"];
            };
        };
        responses: {
            /** @description Issue created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getIssueByID: {
        parameters: {
            query?: {
                /** @description Include full details (dependencies, comments, labels) */
                details?: boolean;
            };
            header?: never;
            path: {
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"] | components["schemas"]["IssueDetails"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getIssue: {
        parameters: {
            query?: {
                /** @description Include full details (dependencies, comments, labels) */
                details?: boolean;
            };
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"] | components["schemas"]["IssueDetails"];
                };
            };
            /** @description Access denied (issue does not belong to project) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateIssue: {
        parameters: {
            query?: never;
            header?: {
                /** @description User performing the action (defaults to "anonymous") */
                "X-Actor"?: components["parameters"]["ActorHeader"];
            };
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateIssueRequest"];
            };
        };
        responses: {
            /** @description Issue updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteIssue: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    closeIssue: {
        parameters: {
            query?: never;
            header?: {
                /** @description User performing the action (defaults to "anonymous") */
                "X-Actor"?: components["parameters"]["ActorHeader"];
            };
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CloseIssueRequest"];
            };
        };
        responses: {
            /** @description Issue closed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    reopenIssue: {
        parameters: {
            query?: never;
            header?: {
                /** @description User performing the action (defaults to "anonymous") */
                "X-Actor"?: components["parameters"]["ActorHeader"];
            };
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Issue reopened */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getReadyWork: {
        parameters: {
            query?: {
                /** @description Filter by issue type */
                type?: components["schemas"]["IssueType"];
                /** @description Filter by priority (0-4) */
                priority?: number;
                /** @description Maximum results to return */
                limit?: number;
                /**
                 * @description Sort policy for ready issues:
                 *     - hybrid (default): Recent issues (<48h) sorted by priority/rank, older issues by age
                 *     - priority: Always sort by priority → rank → created_at
                 *     - oldest: Always sort by created_at (oldest first, for backlog clearing)
                 */
                sort?: "hybrid" | "priority" | "oldest";
            };
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of ready issues */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Issue"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getBlockedIssues: {
        parameters: {
            query?: {
                /** @description Maximum results to return */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of blocked issues with blocking info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockedIssue"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getTeamContext: {
        parameters: {
            query?: {
                /** @description Optional epic ID to scope to children of a specific epic */
                epic_id?: string;
            };
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Team context with issues grouped by role */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamContext"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listAISessions: {
        parameters: {
            query?: {
                /** @description Maximum results to return */
                limit?: number;
                /** @description Pagination offset */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of AI sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAISessions"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createAISession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAISessionRequest"];
            };
        };
        responses: {
            /** @description AI session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AISessionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getAISession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description AI session ID */
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AI session details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AISessionResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteAISession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description AI session ID */
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AI session deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listAIAgents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description AI session ID */
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of AI agents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIAgentResponse"][];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    createAIAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description AI session ID */
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAIAgentRequest"];
            };
        };
        responses: {
            /** @description AI agent created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIAgentResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getAIAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description AI session ID */
                sessionId: string;
                /** @description AI agent ID */
                agentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AI agent details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIAgentResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getDependencies: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dependencies and dependents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DependencyGraph"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    addDependency: {
        parameters: {
            query?: never;
            header?: {
                /** @description User performing the action (defaults to "anonymous") */
                "X-Actor"?: components["parameters"]["ActorHeader"];
            };
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddDependencyRequest"];
            };
        };
        responses: {
            /** @description Dependency added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dependency"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    removeDependency: {
        parameters: {
            query?: never;
            header?: {
                /** @description User performing the action (defaults to "anonymous") */
                "X-Actor"?: components["parameters"]["ActorHeader"];
            };
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
                /** @description ID of the dependency to remove */
                dependsOnId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dependency removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listLabels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of labels */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createLabel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLabelRequest"];
            };
        };
        responses: {
            /** @description Label created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    updateLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Label name */
                labelName: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLabelRequest"];
            };
        };
        responses: {
            /** @description Label updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Label"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Label name */
                labelName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Label deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    addLabelToIssue: {
        parameters: {
            query?: never;
            header?: {
                /** @description User performing the action (defaults to "anonymous") */
                "X-Actor"?: components["parameters"]["ActorHeader"];
            };
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddLabelToIssueRequest"];
            };
        };
        responses: {
            /** @description Label added to issue */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    removeLabelFromIssue: {
        parameters: {
            query?: never;
            header?: {
                /** @description User performing the action (defaults to "anonymous") */
                "X-Actor"?: components["parameters"]["ActorHeader"];
            };
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
                /** @description Label name to remove */
                labelName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Label removed from issue */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of comments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"][];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    addComment: {
        parameters: {
            query?: never;
            header?: {
                /** @description User performing the action (defaults to "anonymous") */
                "X-Actor"?: components["parameters"]["ActorHeader"];
            };
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCommentRequest"];
            };
        };
        responses: {
            /** @description Comment added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
                /** @description Comment ID */
                commentId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCommentRequest"];
            };
        };
        responses: {
            /** @description Comment updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
                /** @description Comment ID */
                commentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comment deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getEvents: {
        parameters: {
            query?: {
                /** @description Maximum events to return */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Project ID */
                projectId: components["parameters"]["ProjectId"];
                /** @description Issue ID */
                issueId: components["parameters"]["IssueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    createPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlanRequest"];
            };
        };
        responses: {
            /** @description Plan created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan with content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanWithContent"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updatePlanContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlanContentRequest"];
            };
        };
        responses: {
            /** @description Content updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanWithContent"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deletePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updatePlanStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlanStatusRequest"];
            };
        };
        responses: {
            /** @description Status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listPlanComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comments list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanComment"][];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createPlanComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlanCommentRequest"];
            };
        };
        responses: {
            /** @description Comment created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanComment"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
}
