# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
#
# goreleaser configuration for arc
# https://goreleaser.com

version: 2

project_name: arc

before:
  hooks:
    - go mod tidy
    # Build frontend before Go compilation
    - bash -c "cd web && bun install && bun run build"

builds:
  - id: arc
    main: ./cmd/arc
    binary: arc
    env:
      - CGO_ENABLED=0
    flags:
      - -tags=webui
    ldflags:
      - -s -w
      - -X github.com/sentiolabs/arc/internal/version.Version={{.Version}}
      - -X github.com/sentiolabs/arc/internal/version.GitCommit={{.Commit}}
      - -X github.com/sentiolabs/arc/internal/version.BuildDate={{.Date}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Other
      order: 999
  filters:
    exclude:
      - "^chore"
      - "^docs"
      - "^test"
      - "^Merge"

# Linux packages (deb, rpm, arch) - published as GitHub release artifacts
nfpms:
  - id: packages
    package_name: arc
    vendor: Sentio Labs
    homepage: "https://github.com/sentiolabs/arc"
    maintainer: "Sentio Labs <packages@sentiolabs.dev>"
    description: "Central issue tracking for AI-assisted coding workflows"
    license: MIT
    formats:
      - deb
      - rpm
      - archlinux
    bindir: /usr/bin
    contents:
      - src: ./README.md
        dst: /usr/share/doc/arc/README.md

release:
  github:
    owner: sentiolabs
    name: arc
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
