// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_sessions.sql

package db

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const countAIAgentsBySession = `-- name: CountAIAgentsBySession :one
SELECT COUNT(*) FROM ai_agents WHERE session_id = ?
`

func (q *Queries) CountAIAgentsBySession(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAIAgentsBySession, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAISessionsByProject = `-- name: CountAISessionsByProject :one
SELECT COUNT(*) FROM ai_sessions WHERE project_id = ?
`

func (q *Queries) CountAISessionsByProject(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAISessionsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAIAgent = `-- name: CreateAIAgent :one
INSERT INTO ai_agents (id, session_id, description, prompt, agent_type, model, status, duration_ms, total_tokens, tool_use_count, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, session_id, description, prompt, agent_type, model, status, duration_ms, total_tokens, tool_use_count, created_at
`

type CreateAIAgentParams struct {
	ID           string         `json:"id"`
	SessionID    string         `json:"session_id"`
	Description  sql.NullString `json:"description"`
	Prompt       sql.NullString `json:"prompt"`
	AgentType    sql.NullString `json:"agent_type"`
	Model        sql.NullString `json:"model"`
	Status       string         `json:"status"`
	DurationMs   sql.NullInt64  `json:"duration_ms"`
	TotalTokens  sql.NullInt64  `json:"total_tokens"`
	ToolUseCount sql.NullInt64  `json:"tool_use_count"`
	CreatedAt    time.Time      `json:"created_at"`
}

func (q *Queries) CreateAIAgent(ctx context.Context, arg CreateAIAgentParams) (*AiAgent, error) {
	row := q.db.QueryRowContext(ctx, createAIAgent,
		arg.ID,
		arg.SessionID,
		arg.Description,
		arg.Prompt,
		arg.AgentType,
		arg.Model,
		arg.Status,
		arg.DurationMs,
		arg.TotalTokens,
		arg.ToolUseCount,
		arg.CreatedAt,
	)
	var i AiAgent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Description,
		&i.Prompt,
		&i.AgentType,
		&i.Model,
		&i.Status,
		&i.DurationMs,
		&i.TotalTokens,
		&i.ToolUseCount,
		&i.CreatedAt,
	)
	return &i, err
}

const createAISession = `-- name: CreateAISession :one
INSERT INTO ai_sessions (id, project_id, transcript_path, cwd, started_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, project_id, transcript_path, cwd, started_at
`

type CreateAISessionParams struct {
	ID             string         `json:"id"`
	ProjectID      string         `json:"project_id"`
	TranscriptPath string         `json:"transcript_path"`
	Cwd            sql.NullString `json:"cwd"`
	StartedAt      time.Time      `json:"started_at"`
}

func (q *Queries) CreateAISession(ctx context.Context, arg CreateAISessionParams) (*AiSession, error) {
	row := q.db.QueryRowContext(ctx, createAISession,
		arg.ID,
		arg.ProjectID,
		arg.TranscriptPath,
		arg.Cwd,
		arg.StartedAt,
	)
	var i AiSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TranscriptPath,
		&i.Cwd,
		&i.StartedAt,
	)
	return &i, err
}

const deleteAISession = `-- name: DeleteAISession :exec
DELETE FROM ai_sessions WHERE id = ?
`

func (q *Queries) DeleteAISession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAISession, id)
	return err
}

const getAIAgent = `-- name: GetAIAgent :one
SELECT id, session_id, description, prompt, agent_type, model, status, duration_ms, total_tokens, tool_use_count, created_at FROM ai_agents WHERE id = ?
`

func (q *Queries) GetAIAgent(ctx context.Context, id string) (*AiAgent, error) {
	row := q.db.QueryRowContext(ctx, getAIAgent, id)
	var i AiAgent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Description,
		&i.Prompt,
		&i.AgentType,
		&i.Model,
		&i.Status,
		&i.DurationMs,
		&i.TotalTokens,
		&i.ToolUseCount,
		&i.CreatedAt,
	)
	return &i, err
}

const getAISession = `-- name: GetAISession :one
SELECT id, project_id, transcript_path, cwd, started_at FROM ai_sessions WHERE id = ?
`

func (q *Queries) GetAISession(ctx context.Context, id string) (*AiSession, error) {
	row := q.db.QueryRowContext(ctx, getAISession, id)
	var i AiSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TranscriptPath,
		&i.Cwd,
		&i.StartedAt,
	)
	return &i, err
}

const getAgentSummariesForSessions = `-- name: GetAgentSummariesForSessions :many
SELECT
  session_id,
  COUNT(*) AS agent_count,
  SUM(CASE WHEN status = 'running' THEN 1 ELSE 0 END) AS running_count,
  SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) AS completed_count,
  SUM(CASE WHEN status = 'error' THEN 1 ELSE 0 END) AS error_count
FROM ai_agents
WHERE session_id IN (/*SLICE:session_ids*/?)
GROUP BY session_id
`

type GetAgentSummariesForSessionsRow struct {
	SessionID      string          `json:"session_id"`
	AgentCount     int64           `json:"agent_count"`
	RunningCount   sql.NullFloat64 `json:"running_count"`
	CompletedCount sql.NullFloat64 `json:"completed_count"`
	ErrorCount     sql.NullFloat64 `json:"error_count"`
}

func (q *Queries) GetAgentSummariesForSessions(ctx context.Context, sessionIds []string) ([]*GetAgentSummariesForSessionsRow, error) {
	query := getAgentSummariesForSessions
	var queryParams []interface{}
	if len(sessionIds) > 0 {
		for _, v := range sessionIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:session_ids*/?", strings.Repeat(",?", len(sessionIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:session_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetAgentSummariesForSessionsRow{}
	for rows.Next() {
		var i GetAgentSummariesForSessionsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.AgentCount,
			&i.RunningCount,
			&i.CompletedCount,
			&i.ErrorCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIAgents = `-- name: ListAIAgents :many
SELECT id, session_id, description, prompt, agent_type, model, status, duration_ms, total_tokens, tool_use_count, created_at FROM ai_agents WHERE session_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListAIAgents(ctx context.Context, sessionID string) ([]*AiAgent, error) {
	rows, err := q.db.QueryContext(ctx, listAIAgents, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*AiAgent{}
	for rows.Next() {
		var i AiAgent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Description,
			&i.Prompt,
			&i.AgentType,
			&i.Model,
			&i.Status,
			&i.DurationMs,
			&i.TotalTokens,
			&i.ToolUseCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAISessionsByProject = `-- name: ListAISessionsByProject :many
SELECT id, project_id, transcript_path, cwd, started_at FROM ai_sessions WHERE project_id = ? ORDER BY started_at DESC LIMIT ? OFFSET ?
`

type ListAISessionsByProjectParams struct {
	ProjectID string `json:"project_id"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

func (q *Queries) ListAISessionsByProject(ctx context.Context, arg ListAISessionsByProjectParams) ([]*AiSession, error) {
	rows, err := q.db.QueryContext(ctx, listAISessionsByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*AiSession{}
	for rows.Next() {
		var i AiSession
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TranscriptPath,
			&i.Cwd,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
