// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package db

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const countComments = `-- name: CountComments :one
SELECT COUNT(*) as count FROM comments WHERE issue_id = ?
`

func (q *Queries) CountComments(ctx context.Context, issueID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countComments, issueID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (issue_id, author, text, created_at)
VALUES (?, ?, ?, ?)
RETURNING id, issue_id, author, text, created_at, updated_at
`

type CreateCommentParams struct {
	IssueID   string    `json:"issue_id"`
	Author    string    `json:"author"`
	Text      string    `json:"text"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (*Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.IssueID,
		arg.Author,
		arg.Text,
		arg.CreatedAt,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Author,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = ?
`

func (q *Queries) DeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const getComment = `-- name: GetComment :one
SELECT id, issue_id, author, text, created_at, updated_at FROM comments WHERE id = ?
`

func (q *Queries) GetComment(ctx context.Context, id int64) (*Comment, error) {
	row := q.db.QueryRowContext(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Author,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getCommentsForIssues = `-- name: GetCommentsForIssues :many
SELECT id, issue_id, author, text, created_at, updated_at FROM comments
WHERE issue_id IN (/*SLICE:issue_ids*/?)
ORDER BY issue_id, created_at ASC
`

func (q *Queries) GetCommentsForIssues(ctx context.Context, issueIds []string) ([]*Comment, error) {
	query := getCommentsForIssues
	var queryParams []interface{}
	if len(issueIds) > 0 {
		for _, v := range issueIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:issue_ids*/?", strings.Repeat(",?", len(issueIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:issue_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Author,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComments = `-- name: ListComments :many
SELECT id, issue_id, author, text, created_at, updated_at FROM comments
WHERE issue_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListComments(ctx context.Context, issueID string) ([]*Comment, error) {
	rows, err := q.db.QueryContext(ctx, listComments, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Author,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :exec
UPDATE comments SET text = ?, updated_at = ?
WHERE id = ?
`

type UpdateCommentParams struct {
	Text      string       `json:"text"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	ID        int64        `json:"id"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) error {
	_, err := q.db.ExecContext(ctx, updateComment, arg.Text, arg.UpdatedAt, arg.ID)
	return err
}
