// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package db

import (
	"context"
	"database/sql"
)

const deleteConfig = `-- name: DeleteConfig :exec
DELETE FROM config WHERE workspace_id = ? AND key = ?
`

type DeleteConfigParams struct {
	WorkspaceID string `json:"workspace_id"`
	Key         string `json:"key"`
}

func (q *Queries) DeleteConfig(ctx context.Context, arg DeleteConfigParams) error {
	_, err := q.db.ExecContext(ctx, deleteConfig, arg.WorkspaceID, arg.Key)
	return err
}

const deleteGlobalConfig = `-- name: DeleteGlobalConfig :exec
DELETE FROM global_config WHERE key = ?
`

func (q *Queries) DeleteGlobalConfig(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteGlobalConfig, key)
	return err
}

const getAllConfig = `-- name: GetAllConfig :many
SELECT key, value FROM config WHERE workspace_id = ?
`

type GetAllConfigRow struct {
	Key   string         `json:"key"`
	Value sql.NullString `json:"value"`
}

func (q *Queries) GetAllConfig(ctx context.Context, workspaceID string) ([]*GetAllConfigRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllConfig, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetAllConfigRow{}
	for rows.Next() {
		var i GetAllConfigRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllGlobalConfig = `-- name: GetAllGlobalConfig :many
SELECT key, value FROM global_config
`

func (q *Queries) GetAllGlobalConfig(ctx context.Context) ([]*GlobalConfig, error) {
	rows, err := q.db.QueryContext(ctx, getAllGlobalConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GlobalConfig{}
	for rows.Next() {
		var i GlobalConfig
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConfig = `-- name: GetConfig :one
SELECT value FROM config WHERE workspace_id = ? AND key = ?
`

type GetConfigParams struct {
	WorkspaceID string `json:"workspace_id"`
	Key         string `json:"key"`
}

func (q *Queries) GetConfig(ctx context.Context, arg GetConfigParams) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getConfig, arg.WorkspaceID, arg.Key)
	var value sql.NullString
	err := row.Scan(&value)
	return value, err
}

const getGlobalConfig = `-- name: GetGlobalConfig :one
SELECT value FROM global_config WHERE key = ?
`

func (q *Queries) GetGlobalConfig(ctx context.Context, key string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getGlobalConfig, key)
	var value sql.NullString
	err := row.Scan(&value)
	return value, err
}

const setConfig = `-- name: SetConfig :exec
INSERT INTO config (workspace_id, key, value)
VALUES (?, ?, ?)
ON CONFLICT(workspace_id, key) DO UPDATE SET value = excluded.value
`

type SetConfigParams struct {
	WorkspaceID string         `json:"workspace_id"`
	Key         string         `json:"key"`
	Value       sql.NullString `json:"value"`
}

func (q *Queries) SetConfig(ctx context.Context, arg SetConfigParams) error {
	_, err := q.db.ExecContext(ctx, setConfig, arg.WorkspaceID, arg.Key, arg.Value)
	return err
}

const setGlobalConfig = `-- name: SetGlobalConfig :exec
INSERT INTO global_config (key, value)
VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetGlobalConfigParams struct {
	Key   string         `json:"key"`
	Value sql.NullString `json:"value"`
}

func (q *Queries) SetGlobalConfig(ctx context.Context, arg SetGlobalConfigParams) error {
	_, err := q.db.ExecContext(ctx, setGlobalConfig, arg.Key, arg.Value)
	return err
}
