// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countEvents = `-- name: CountEvents :one
SELECT COUNT(*) as count FROM events WHERE issue_id = ?
`

func (q *Queries) CountEvents(ctx context.Context, issueID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEvents, issueID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (issue_id, event_type, actor, old_value, new_value, comment, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateEventParams struct {
	IssueID   string         `json:"issue_id"`
	EventType string         `json:"event_type"`
	Actor     string         `json:"actor"`
	OldValue  sql.NullString `json:"old_value"`
	NewValue  sql.NullString `json:"new_value"`
	Comment   sql.NullString `json:"comment"`
	CreatedAt time.Time      `json:"created_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.ExecContext(ctx, createEvent,
		arg.IssueID,
		arg.EventType,
		arg.Actor,
		arg.OldValue,
		arg.NewValue,
		arg.Comment,
		arg.CreatedAt,
	)
	return err
}

const deleteEventsByIssue = `-- name: DeleteEventsByIssue :exec
DELETE FROM events WHERE issue_id = ?
`

func (q *Queries) DeleteEventsByIssue(ctx context.Context, issueID string) error {
	_, err := q.db.ExecContext(ctx, deleteEventsByIssue, issueID)
	return err
}

const getEvents = `-- name: GetEvents :many
SELECT id, issue_id, event_type, actor, old_value, new_value, comment, created_at FROM events
WHERE issue_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type GetEventsParams struct {
	IssueID string `json:"issue_id"`
	Limit   int64  `json:"limit"`
}

func (q *Queries) GetEvents(ctx context.Context, arg GetEventsParams) ([]*Event, error) {
	rows, err := q.db.QueryContext(ctx, getEvents, arg.IssueID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.EventType,
			&i.Actor,
			&i.OldValue,
			&i.NewValue,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentEvents = `-- name: GetRecentEvents :many
SELECT id, issue_id, event_type, actor, old_value, new_value, comment, created_at FROM events
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) GetRecentEvents(ctx context.Context, limit int64) ([]*Event, error) {
	rows, err := q.db.QueryContext(ctx, getRecentEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.EventType,
			&i.Actor,
			&i.OldValue,
			&i.NewValue,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
