// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: governance_history.sql

package db

import (
	"context"
)

const listExecutionEvidenceRecords = `-- name: ListExecutionEvidenceRecords :many
SELECT result FROM execution_evidence
WHERE project_id = ? AND issue_id = ? ORDER BY created_at, id LIMIT ? OFFSET ?
`

type ListExecutionEvidenceRecordsParams struct {
	ProjectID string `json:"project_id"`
	IssueID   string `json:"issue_id"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

func (q *Queries) ListExecutionEvidenceRecords(ctx context.Context, arg ListExecutionEvidenceRecordsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listExecutionEvidenceRecords,
		arg.ProjectID,
		arg.IssueID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var result string
		if err := rows.Scan(&result); err != nil {
			return nil, err
		}
		items = append(items, result)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanAdoptionRecords = `-- name: ListPlanAdoptionRecords :many
SELECT result FROM plan_adoptions
WHERE project_id = ? AND container_id = ? ORDER BY created_at, id LIMIT ? OFFSET ?
`

type ListPlanAdoptionRecordsParams struct {
	ProjectID   string `json:"project_id"`
	ContainerID string `json:"container_id"`
	Limit       int64  `json:"limit"`
	Offset      int64  `json:"offset"`
}

func (q *Queries) ListPlanAdoptionRecords(ctx context.Context, arg ListPlanAdoptionRecordsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPlanAdoptionRecords,
		arg.ProjectID,
		arg.ContainerID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var result string
		if err := rows.Scan(&result); err != nil {
			return nil, err
		}
		items = append(items, result)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
