// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issues.sql

package db

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const closeIssue = `-- name: CloseIssue :exec
UPDATE issues SET
    status = 'closed',
    closed_at = ?,
    close_reason = ?,
    updated_at = ?
WHERE id = ?
`

type CloseIssueParams struct {
	ClosedAt    sql.NullTime   `json:"closed_at"`
	CloseReason sql.NullString `json:"close_reason"`
	UpdatedAt   time.Time      `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) CloseIssue(ctx context.Context, arg CloseIssueParams) error {
	_, err := q.db.ExecContext(ctx, closeIssue,
		arg.ClosedAt,
		arg.CloseReason,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const countIssuesByID = `-- name: CountIssuesByID :one
SELECT COUNT(*) as count FROM issues WHERE id = ?
`

func (q *Queries) CountIssuesByID(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIssuesByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIssuesByProject = `-- name: CountIssuesByProject :one
SELECT COUNT(*) as count FROM issues WHERE project_id = ?
`

func (q *Queries) CountIssuesByProject(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIssuesByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIssuesByStatus = `-- name: CountIssuesByStatus :one
SELECT COUNT(*) as count FROM issues WHERE project_id = ? AND status = ?
`

type CountIssuesByStatusParams struct {
	ProjectID string `json:"project_id"`
	Status    string `json:"status"`
}

func (q *Queries) CountIssuesByStatus(ctx context.Context, arg CountIssuesByStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIssuesByStatus, arg.ProjectID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIssue = `-- name: CreateIssue :exec
INSERT INTO issues (
    id, project_id, title, description,
    status, priority, issue_type, assignee, ai_session_id, external_ref,
    created_at, updated_at, closed_at, close_reason
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateIssueParams struct {
	ID          string         `json:"id"`
	ProjectID   string         `json:"project_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	Priority    int64          `json:"priority"`
	IssueType   string         `json:"issue_type"`
	Assignee    sql.NullString `json:"assignee"`
	AiSessionID sql.NullString `json:"ai_session_id"`
	ExternalRef sql.NullString `json:"external_ref"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	ClosedAt    sql.NullTime   `json:"closed_at"`
	CloseReason sql.NullString `json:"close_reason"`
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) error {
	_, err := q.db.ExecContext(ctx, createIssue,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.IssueType,
		arg.Assignee,
		arg.AiSessionID,
		arg.ExternalRef,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ClosedAt,
		arg.CloseReason,
	)
	return err
}

const deleteIssue = `-- name: DeleteIssue :exec
DELETE FROM issues WHERE id = ?
`

func (q *Queries) DeleteIssue(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteIssue, id)
	return err
}

const getIssue = `-- name: GetIssue :one
SELECT id, project_id, title, description, status, priority, issue_type, assignee, ai_session_id, external_ref, rank, created_at, updated_at, closed_at, close_reason FROM issues WHERE id = ?
`

func (q *Queries) GetIssue(ctx context.Context, id string) (*Issue, error) {
	row := q.db.QueryRowContext(ctx, getIssue, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.IssueType,
		&i.Assignee,
		&i.AiSessionID,
		&i.ExternalRef,
		&i.Rank,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.CloseReason,
	)
	return &i, err
}

const getIssueByExternalRef = `-- name: GetIssueByExternalRef :one
SELECT id, project_id, title, description, status, priority, issue_type, assignee, ai_session_id, external_ref, rank, created_at, updated_at, closed_at, close_reason FROM issues WHERE external_ref = ?
`

func (q *Queries) GetIssueByExternalRef(ctx context.Context, externalRef sql.NullString) (*Issue, error) {
	row := q.db.QueryRowContext(ctx, getIssueByExternalRef, externalRef)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.IssueType,
		&i.Assignee,
		&i.AiSessionID,
		&i.ExternalRef,
		&i.Rank,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.CloseReason,
	)
	return &i, err
}

const getOpenNonBlockedIssues = `-- name: GetOpenNonBlockedIssues :many
SELECT i.id, i.project_id, i.title, i.description, i.status, i.priority, i.issue_type, i.assignee, i.ai_session_id, i.external_ref, i.rank, i.created_at, i.updated_at, i.closed_at, i.close_reason FROM issues i
LEFT JOIN dependencies d ON d.issue_id = i.id AND d.type = 'blocks'
LEFT JOIN issues blocker ON d.depends_on_id = blocker.id AND blocker.status != 'closed'
WHERE i.project_id = ?
  AND i.status IN ('open', 'in_progress')
GROUP BY i.id
HAVING COUNT(blocker.id) = 0
ORDER BY i.priority ASC, i.updated_at DESC
LIMIT ?
`

type GetOpenNonBlockedIssuesParams struct {
	ProjectID string `json:"project_id"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) GetOpenNonBlockedIssues(ctx context.Context, arg GetOpenNonBlockedIssuesParams) ([]*Issue, error) {
	rows, err := q.db.QueryContext(ctx, getOpenNonBlockedIssues, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.IssueType,
			&i.Assignee,
			&i.AiSessionID,
			&i.ExternalRef,
			&i.Rank,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.CloseReason,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReadyIssuesHybrid = `-- name: GetReadyIssuesHybrid :many
SELECT i.id, i.project_id, i.title, i.description, i.status, i.priority, i.issue_type, i.assignee, i.ai_session_id, i.external_ref, i.rank, i.created_at, i.updated_at, i.closed_at, i.close_reason FROM issues i
LEFT JOIN dependencies d ON d.issue_id = i.id AND d.type = 'blocks'
LEFT JOIN issues blocker ON d.depends_on_id = blocker.id AND blocker.status != 'closed'
WHERE i.project_id = ?
  AND i.status IN ('open', 'in_progress')
GROUP BY i.id
HAVING COUNT(blocker.id) = 0
ORDER BY
  CASE WHEN i.updated_at >= datetime('now', '-48 hours') THEN 0 ELSE 1 END ASC,
  CASE WHEN i.updated_at >= datetime('now', '-48 hours')
       THEN i.priority
       ELSE 999 END ASC,
  CASE WHEN i.updated_at >= datetime('now', '-48 hours')
       THEN CASE WHEN i.rank = 0 THEN 999999 ELSE i.rank END
       ELSE 999999 END ASC,
  CASE WHEN i.updated_at >= datetime('now', '-48 hours')
       THEN datetime('9999-12-31')
       ELSE i.created_at END ASC
LIMIT ?
`

type GetReadyIssuesHybridParams struct {
	ProjectID string `json:"project_id"`
	Limit     int64  `json:"limit"`
}

// Hybrid sort: recent issues (<48h) by priority/rank, older issues by age.
// Uses CASE to create two sorting groups, then appropriate sub-ordering within each.
// Note: Only 'blocks' dependencies are blocking; parent-child is organizational only.
func (q *Queries) GetReadyIssuesHybrid(ctx context.Context, arg GetReadyIssuesHybridParams) ([]*Issue, error) {
	rows, err := q.db.QueryContext(ctx, getReadyIssuesHybrid, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.IssueType,
			&i.Assignee,
			&i.AiSessionID,
			&i.ExternalRef,
			&i.Rank,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.CloseReason,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReadyIssuesOldest = `-- name: GetReadyIssuesOldest :many
SELECT i.id, i.project_id, i.title, i.description, i.status, i.priority, i.issue_type, i.assignee, i.ai_session_id, i.external_ref, i.rank, i.created_at, i.updated_at, i.closed_at, i.close_reason FROM issues i
LEFT JOIN dependencies d ON d.issue_id = i.id AND d.type = 'blocks'
LEFT JOIN issues blocker ON d.depends_on_id = blocker.id AND blocker.status != 'closed'
WHERE i.project_id = ?
  AND i.status IN ('open', 'in_progress')
GROUP BY i.id
HAVING COUNT(blocker.id) = 0
ORDER BY i.created_at ASC
LIMIT ?
`

type GetReadyIssuesOldestParams struct {
	ProjectID string `json:"project_id"`
	Limit     int64  `json:"limit"`
}

// Oldest-first sort: for backlog clearing.
// Note: Only 'blocks' dependencies are blocking; parent-child is organizational only.
func (q *Queries) GetReadyIssuesOldest(ctx context.Context, arg GetReadyIssuesOldestParams) ([]*Issue, error) {
	rows, err := q.db.QueryContext(ctx, getReadyIssuesOldest, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.IssueType,
			&i.Assignee,
			&i.AiSessionID,
			&i.ExternalRef,
			&i.Rank,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.CloseReason,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReadyIssuesPriority = `-- name: GetReadyIssuesPriority :many
SELECT i.id, i.project_id, i.title, i.description, i.status, i.priority, i.issue_type, i.assignee, i.ai_session_id, i.external_ref, i.rank, i.created_at, i.updated_at, i.closed_at, i.close_reason FROM issues i
LEFT JOIN dependencies d ON d.issue_id = i.id AND d.type = 'blocks'
LEFT JOIN issues blocker ON d.depends_on_id = blocker.id AND blocker.status != 'closed'
WHERE i.project_id = ?
  AND i.status IN ('open', 'in_progress')
GROUP BY i.id
HAVING COUNT(blocker.id) = 0
ORDER BY
  i.priority ASC,
  CASE WHEN i.rank = 0 THEN 999999 ELSE i.rank END ASC,
  i.created_at ASC
LIMIT ?
`

type GetReadyIssuesPriorityParams struct {
	ProjectID string `json:"project_id"`
	Limit     int64  `json:"limit"`
}

// Priority-first sort: priority -> rank -> created_at.
// Note: Only 'blocks' dependencies are blocking; parent-child is organizational only.
func (q *Queries) GetReadyIssuesPriority(ctx context.Context, arg GetReadyIssuesPriorityParams) ([]*Issue, error) {
	rows, err := q.db.QueryContext(ctx, getReadyIssuesPriority, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.IssueType,
			&i.Assignee,
			&i.AiSessionID,
			&i.ExternalRef,
			&i.Rank,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.CloseReason,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesFiltered = `-- name: ListIssuesFiltered :many
SELECT i.id, i.project_id, i.title, i.description, i.status, i.priority,
       i.issue_type, i.assignee, i.ai_session_id, i.external_ref, i.rank,
       i.created_at, i.updated_at, i.closed_at, i.close_reason
FROM issues i
LEFT JOIN dependencies d ON d.issue_id = i.id AND d.type = 'parent-child'
WHERE i.project_id = ?1
  AND i.status IN (/*SLICE:statuses*/?)
  AND i.issue_type IN (/*SLICE:issue_types*/?)
  AND i.priority IN (/*SLICE:priorities*/?)
  AND (?5 IS NULL OR i.assignee = ?5)
  AND (?6 IS NULL OR i.ai_session_id = ?6)
  AND (?7 IS NULL OR d.depends_on_id = ?7)
ORDER BY i.priority ASC, i.updated_at DESC
LIMIT ?9 OFFSET ?8
`

type ListIssuesFilteredParams struct {
	ProjectID   string      `json:"project_id"`
	Statuses    []string    `json:"statuses"`
	IssueTypes  []string    `json:"issue_types"`
	Priorities  []int64     `json:"priorities"`
	Assignee    interface{} `json:"assignee"`
	AiSessionID interface{} `json:"ai_session_id"`
	ParentID    interface{} `json:"parent_id"`
	Offset      int64       `json:"offset"`
	Limit       int64       `json:"limit"`
}

// Composable filter query: slices use IN for multi-select, narg for optional scalars.
// The LEFT JOIN on dependencies is only effective when parent_id is non-NULL.
func (q *Queries) ListIssuesFiltered(ctx context.Context, arg ListIssuesFilteredParams) ([]*Issue, error) {
	query := listIssuesFiltered
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ProjectID)
	if len(arg.Statuses) > 0 {
		for _, v := range arg.Statuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:statuses*/?", strings.Repeat(",?", len(arg.Statuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:statuses*/?", "NULL", 1)
	}
	if len(arg.IssueTypes) > 0 {
		for _, v := range arg.IssueTypes {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:issue_types*/?", strings.Repeat(",?", len(arg.IssueTypes))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:issue_types*/?", "NULL", 1)
	}
	if len(arg.Priorities) > 0 {
		for _, v := range arg.Priorities {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:priorities*/?", strings.Repeat(",?", len(arg.Priorities))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:priorities*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Assignee)
	queryParams = append(queryParams, arg.AiSessionID)
	queryParams = append(queryParams, arg.ParentID)
	queryParams = append(queryParams, arg.Offset)
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.IssueType,
			&i.Assignee,
			&i.AiSessionID,
			&i.ExternalRef,
			&i.Rank,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.CloseReason,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenIssue = `-- name: ReopenIssue :exec
UPDATE issues SET
    status = 'open',
    closed_at = NULL,
    close_reason = NULL,
    updated_at = ?
WHERE id = ?
`

type ReopenIssueParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) ReopenIssue(ctx context.Context, arg ReopenIssueParams) error {
	_, err := q.db.ExecContext(ctx, reopenIssue, arg.UpdatedAt, arg.ID)
	return err
}

const searchIssues = `-- name: SearchIssues :many
SELECT id, project_id, title, description, status, priority, issue_type, assignee, ai_session_id, external_ref, rank, created_at, updated_at, closed_at, close_reason FROM issues
WHERE project_id = ?
  AND (title LIKE ? OR description LIKE ?)
ORDER BY priority ASC, updated_at DESC
LIMIT ? OFFSET ?
`

type SearchIssuesParams struct {
	ProjectID   string         `json:"project_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Limit       int64          `json:"limit"`
	Offset      int64          `json:"offset"`
}

func (q *Queries) SearchIssues(ctx context.Context, arg SearchIssuesParams) ([]*Issue, error) {
	rows, err := q.db.QueryContext(ctx, searchIssues,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.IssueType,
			&i.Assignee,
			&i.AiSessionID,
			&i.ExternalRef,
			&i.Rank,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.CloseReason,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIssueAISessionID = `-- name: UpdateIssueAISessionID :exec
UPDATE issues SET ai_session_id = ?, updated_at = ? WHERE id = ?
`

type UpdateIssueAISessionIDParams struct {
	AiSessionID sql.NullString `json:"ai_session_id"`
	UpdatedAt   time.Time      `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateIssueAISessionID(ctx context.Context, arg UpdateIssueAISessionIDParams) error {
	_, err := q.db.ExecContext(ctx, updateIssueAISessionID, arg.AiSessionID, arg.UpdatedAt, arg.ID)
	return err
}

const updateIssueAssignee = `-- name: UpdateIssueAssignee :exec
UPDATE issues SET assignee = ?, updated_at = ? WHERE id = ?
`

type UpdateIssueAssigneeParams struct {
	Assignee  sql.NullString `json:"assignee"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateIssueAssignee(ctx context.Context, arg UpdateIssueAssigneeParams) error {
	_, err := q.db.ExecContext(ctx, updateIssueAssignee, arg.Assignee, arg.UpdatedAt, arg.ID)
	return err
}

const updateIssueDescription = `-- name: UpdateIssueDescription :exec
UPDATE issues SET description = ?, updated_at = ? WHERE id = ?
`

type UpdateIssueDescriptionParams struct {
	Description sql.NullString `json:"description"`
	UpdatedAt   time.Time      `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateIssueDescription(ctx context.Context, arg UpdateIssueDescriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateIssueDescription, arg.Description, arg.UpdatedAt, arg.ID)
	return err
}

const updateIssueExternalRef = `-- name: UpdateIssueExternalRef :exec
UPDATE issues SET external_ref = ?, updated_at = ? WHERE id = ?
`

type UpdateIssueExternalRefParams struct {
	ExternalRef sql.NullString `json:"external_ref"`
	UpdatedAt   time.Time      `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateIssueExternalRef(ctx context.Context, arg UpdateIssueExternalRefParams) error {
	_, err := q.db.ExecContext(ctx, updateIssueExternalRef, arg.ExternalRef, arg.UpdatedAt, arg.ID)
	return err
}

const updateIssuePriority = `-- name: UpdateIssuePriority :exec
UPDATE issues SET priority = ?, updated_at = ? WHERE id = ?
`

type UpdateIssuePriorityParams struct {
	Priority  int64     `json:"priority"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateIssuePriority(ctx context.Context, arg UpdateIssuePriorityParams) error {
	_, err := q.db.ExecContext(ctx, updateIssuePriority, arg.Priority, arg.UpdatedAt, arg.ID)
	return err
}

const updateIssueRank = `-- name: UpdateIssueRank :exec
UPDATE issues SET rank = ?, updated_at = ? WHERE id = ?
`

type UpdateIssueRankParams struct {
	Rank      int64     `json:"rank"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateIssueRank(ctx context.Context, arg UpdateIssueRankParams) error {
	_, err := q.db.ExecContext(ctx, updateIssueRank, arg.Rank, arg.UpdatedAt, arg.ID)
	return err
}

const updateIssueStatus = `-- name: UpdateIssueStatus :exec
UPDATE issues SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateIssueStatusParams struct {
	Status    string    `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateIssueStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const updateIssueTitle = `-- name: UpdateIssueTitle :exec
UPDATE issues SET title = ?, updated_at = ? WHERE id = ?
`

type UpdateIssueTitleParams struct {
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateIssueTitle(ctx context.Context, arg UpdateIssueTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateIssueTitle, arg.Title, arg.UpdatedAt, arg.ID)
	return err
}

const updateIssueType = `-- name: UpdateIssueType :exec
UPDATE issues SET issue_type = ?, updated_at = ? WHERE id = ?
`

type UpdateIssueTypeParams struct {
	IssueType string    `json:"issue_type"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateIssueType(ctx context.Context, arg UpdateIssueTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateIssueType, arg.IssueType, arg.UpdatedAt, arg.ID)
	return err
}
