// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: labels.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const addLabelToIssue = `-- name: AddLabelToIssue :exec
INSERT INTO issue_labels (issue_id, label)
VALUES (?, ?)
ON CONFLICT(issue_id, label) DO NOTHING
`

type AddLabelToIssueParams struct {
	IssueID string `json:"issue_id"`
	Label   string `json:"label"`
}

func (q *Queries) AddLabelToIssue(ctx context.Context, arg AddLabelToIssueParams) error {
	_, err := q.db.ExecContext(ctx, addLabelToIssue, arg.IssueID, arg.Label)
	return err
}

const createLabel = `-- name: CreateLabel :exec
INSERT INTO labels (workspace_id, name, color, description)
VALUES (?, ?, ?, ?)
ON CONFLICT(workspace_id, name) DO UPDATE SET
    color = excluded.color,
    description = excluded.description
`

type CreateLabelParams struct {
	WorkspaceID string         `json:"workspace_id"`
	Name        string         `json:"name"`
	Color       sql.NullString `json:"color"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) error {
	_, err := q.db.ExecContext(ctx, createLabel,
		arg.WorkspaceID,
		arg.Name,
		arg.Color,
		arg.Description,
	)
	return err
}

const deleteIssueLabels = `-- name: DeleteIssueLabels :exec
DELETE FROM issue_labels WHERE issue_id = ?
`

func (q *Queries) DeleteIssueLabels(ctx context.Context, issueID string) error {
	_, err := q.db.ExecContext(ctx, deleteIssueLabels, issueID)
	return err
}

const deleteLabel = `-- name: DeleteLabel :exec
DELETE FROM labels WHERE workspace_id = ? AND name = ?
`

type DeleteLabelParams struct {
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
}

func (q *Queries) DeleteLabel(ctx context.Context, arg DeleteLabelParams) error {
	_, err := q.db.ExecContext(ctx, deleteLabel, arg.WorkspaceID, arg.Name)
	return err
}

const getIssueLabels = `-- name: GetIssueLabels :many
SELECT label FROM issue_labels WHERE issue_id = ? ORDER BY label
`

func (q *Queries) GetIssueLabels(ctx context.Context, issueID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getIssueLabels, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIssuesByLabel = `-- name: GetIssuesByLabel :many
SELECT i.id, i.workspace_id, i.title, i.description, i.status, i.priority, i.issue_type, i.assignee, i.external_ref, i.rank, i.created_at, i.updated_at, i.closed_at, i.close_reason FROM issues i
JOIN issue_labels il ON i.id = il.issue_id
WHERE il.label = ?
ORDER BY i.priority ASC, i.updated_at DESC
`

func (q *Queries) GetIssuesByLabel(ctx context.Context, label string) ([]*Issue, error) {
	rows, err := q.db.QueryContext(ctx, getIssuesByLabel, label)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.IssueType,
			&i.Assignee,
			&i.ExternalRef,
			&i.Rank,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.CloseReason,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLabel = `-- name: GetLabel :one
SELECT workspace_id, name, color, description FROM labels WHERE workspace_id = ? AND name = ?
`

type GetLabelParams struct {
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
}

func (q *Queries) GetLabel(ctx context.Context, arg GetLabelParams) (*Label, error) {
	row := q.db.QueryRowContext(ctx, getLabel, arg.WorkspaceID, arg.Name)
	var i Label
	err := row.Scan(
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.Description,
	)
	return &i, err
}

const getLabelsForIssues = `-- name: GetLabelsForIssues :many
SELECT issue_id, label FROM issue_labels
WHERE issue_id IN (/*SLICE:issue_ids*/?)
ORDER BY issue_id, label
`

func (q *Queries) GetLabelsForIssues(ctx context.Context, issueIds []string) ([]*IssueLabel, error) {
	query := getLabelsForIssues
	var queryParams []interface{}
	if len(issueIds) > 0 {
		for _, v := range issueIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:issue_ids*/?", strings.Repeat(",?", len(issueIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:issue_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*IssueLabel{}
	for rows.Next() {
		var i IssueLabel
		if err := rows.Scan(&i.IssueID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabels = `-- name: ListLabels :many
SELECT workspace_id, name, color, description FROM labels WHERE workspace_id = ? ORDER BY name
`

func (q *Queries) ListLabels(ctx context.Context, workspaceID string) ([]*Label, error) {
	rows, err := q.db.QueryContext(ctx, listLabels, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Label{}
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Name,
			&i.Color,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeLabelFromIssue = `-- name: RemoveLabelFromIssue :exec
DELETE FROM issue_labels WHERE issue_id = ? AND label = ?
`

type RemoveLabelFromIssueParams struct {
	IssueID string `json:"issue_id"`
	Label   string `json:"label"`
}

func (q *Queries) RemoveLabelFromIssue(ctx context.Context, arg RemoveLabelFromIssueParams) error {
	_, err := q.db.ExecContext(ctx, removeLabelFromIssue, arg.IssueID, arg.Label)
	return err
}

const updateLabel = `-- name: UpdateLabel :exec
UPDATE labels SET color = ?, description = ?
WHERE workspace_id = ? AND name = ?
`

type UpdateLabelParams struct {
	Color       sql.NullString `json:"color"`
	Description sql.NullString `json:"description"`
	WorkspaceID string         `json:"workspace_id"`
	Name        string         `json:"name"`
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) error {
	_, err := q.db.ExecContext(ctx, updateLabel,
		arg.Color,
		arg.Description,
		arg.WorkspaceID,
		arg.Name,
	)
	return err
}
