// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type BlockedIssuesCache struct {
	IssueID        string         `json:"issue_id"`
	BlockedByCount int64          `json:"blocked_by_count"`
	BlockedByIds   sql.NullString `json:"blocked_by_ids"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type ChildCounter struct {
	ParentID  string `json:"parent_id"`
	LastChild int64  `json:"last_child"`
}

type Comment struct {
	ID        int64        `json:"id"`
	IssueID   string       `json:"issue_id"`
	Author    string       `json:"author"`
	Text      string       `json:"text"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Config struct {
	WorkspaceID string         `json:"workspace_id"`
	Key         string         `json:"key"`
	Value       sql.NullString `json:"value"`
}

type Dependency struct {
	IssueID     string         `json:"issue_id"`
	DependsOnID string         `json:"depends_on_id"`
	Type        string         `json:"type"`
	CreatedAt   time.Time      `json:"created_at"`
	CreatedBy   sql.NullString `json:"created_by"`
}

type Event struct {
	ID        int64          `json:"id"`
	IssueID   string         `json:"issue_id"`
	EventType string         `json:"event_type"`
	Actor     string         `json:"actor"`
	OldValue  sql.NullString `json:"old_value"`
	NewValue  sql.NullString `json:"new_value"`
	Comment   sql.NullString `json:"comment"`
	CreatedAt time.Time      `json:"created_at"`
}

type GlobalConfig struct {
	Key   string         `json:"key"`
	Value sql.NullString `json:"value"`
}

type Issue struct {
	ID          string         `json:"id"`
	WorkspaceID string         `json:"workspace_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	Priority    int64          `json:"priority"`
	IssueType   string         `json:"issue_type"`
	Assignee    sql.NullString `json:"assignee"`
	ExternalRef sql.NullString `json:"external_ref"`
	Rank        int64          `json:"rank"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	ClosedAt    sql.NullTime   `json:"closed_at"`
	CloseReason sql.NullString `json:"close_reason"`
}

type IssueLabel struct {
	IssueID string `json:"issue_id"`
	Label   string `json:"label"`
}

type Label struct {
	WorkspaceID string         `json:"workspace_id"`
	Name        string         `json:"name"`
	Color       sql.NullString `json:"color"`
	Description sql.NullString `json:"description"`
}

type Workspace struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Path        sql.NullString `json:"path"`
	Description sql.NullString `json:"description"`
	Prefix      string         `json:"prefix"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}
