// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type AdoptionIdempotency struct {
	ProjectID   string `json:"project_id"`
	ContainerID string `json:"container_id"`
	Key         string `json:"key"`
	Fingerprint string `json:"fingerprint"`
	AdoptionID  string `json:"adoption_id"`
}

type AiAgent struct {
	ID           string         `json:"id"`
	SessionID    string         `json:"session_id"`
	Description  sql.NullString `json:"description"`
	Prompt       sql.NullString `json:"prompt"`
	AgentType    sql.NullString `json:"agent_type"`
	Model        sql.NullString `json:"model"`
	Status       string         `json:"status"`
	DurationMs   sql.NullInt64  `json:"duration_ms"`
	TotalTokens  sql.NullInt64  `json:"total_tokens"`
	ToolUseCount sql.NullInt64  `json:"tool_use_count"`
	CreatedAt    time.Time      `json:"created_at"`
}

type AiSession struct {
	ID             string         `json:"id"`
	ProjectID      string         `json:"project_id"`
	TranscriptPath string         `json:"transcript_path"`
	Cwd            sql.NullString `json:"cwd"`
	StartedAt      time.Time      `json:"started_at"`
}

type BlockedIssuesCache struct {
	IssueID        string         `json:"issue_id"`
	BlockedByCount int64          `json:"blocked_by_count"`
	BlockedByIds   sql.NullString `json:"blocked_by_ids"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type ChildCounter struct {
	ParentID  string `json:"parent_id"`
	LastChild int64  `json:"last_child"`
}

type Comment struct {
	ID        int64        `json:"id"`
	IssueID   string       `json:"issue_id"`
	Author    string       `json:"author"`
	Text      string       `json:"text"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Config struct {
	ProjectID string         `json:"project_id"`
	Key       string         `json:"key"`
	Value     sql.NullString `json:"value"`
}

type Dependency struct {
	IssueID     string         `json:"issue_id"`
	DependsOnID string         `json:"depends_on_id"`
	Type        string         `json:"type"`
	CreatedAt   time.Time      `json:"created_at"`
	CreatedBy   sql.NullString `json:"created_by"`
}

type Event struct {
	ID        int64          `json:"id"`
	IssueID   string         `json:"issue_id"`
	EventType string         `json:"event_type"`
	Actor     string         `json:"actor"`
	OldValue  sql.NullString `json:"old_value"`
	NewValue  sql.NullString `json:"new_value"`
	Comment   sql.NullString `json:"comment"`
	CreatedAt time.Time      `json:"created_at"`
}

type ExecutionEvidence struct {
	ID        string    `json:"id"`
	ProjectID string    `json:"project_id"`
	IssueID   string    `json:"issue_id"`
	Result    string    `json:"result"`
	CreatedAt time.Time `json:"created_at"`
}

type GlobalConfig struct {
	Key   string         `json:"key"`
	Value sql.NullString `json:"value"`
}

type Issue struct {
	ID                    string         `json:"id"`
	ProjectID             string         `json:"project_id"`
	Title                 string         `json:"title"`
	Description           sql.NullString `json:"description"`
	Status                string         `json:"status"`
	Priority              int64          `json:"priority"`
	IssueType             string         `json:"issue_type"`
	AiSessionID           sql.NullString `json:"ai_session_id"`
	ExternalRef           sql.NullString `json:"external_ref"`
	Rank                  int64          `json:"rank"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	ClosedAt              sql.NullTime   `json:"closed_at"`
	CloseReason           sql.NullString `json:"close_reason"`
	ContractVersion       int64          `json:"contract_version"`
	GoverningPlanID       sql.NullString `json:"governing_plan_id"`
	GoverningPlanRevision sql.NullInt64  `json:"governing_plan_revision"`
}

type IssueGovernanceHistory struct {
	ProjectID string `json:"project_id"`
	IssueID   string `json:"issue_id"`
	PlanID    string `json:"plan_id"`
	Revision  int64  `json:"revision"`
}

type IssueLabel struct {
	IssueID string `json:"issue_id"`
	Label   string `json:"label"`
}

type Label struct {
	Name        string         `json:"name"`
	Color       sql.NullString `json:"color"`
	Description sql.NullString `json:"description"`
}

type LegacyPlan struct {
	ID        string    `json:"id"`
	FilePath  string    `json:"file_path"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type LegacyPlanComment struct {
	ID            string         `json:"id"`
	PlanID        string         `json:"plan_id"`
	LineNumber    sql.NullInt64  `json:"line_number"`
	Content       string         `json:"content"`
	CreatedAt     time.Time      `json:"created_at"`
	LineStart     sql.NullInt64  `json:"line_start"`
	LineEnd       sql.NullInt64  `json:"line_end"`
	QuotedText    sql.NullString `json:"quoted_text"`
	Occurrence    sql.NullInt64  `json:"occurrence"`
	HeadingSlug   sql.NullString `json:"heading_slug"`
	ContextBefore sql.NullString `json:"context_before"`
	ContextAfter  sql.NullString `json:"context_after"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	ResolvedAt    sql.NullTime   `json:"resolved_at"`
}

type Plan struct {
	ID                     string         `json:"id"`
	ProjectID              string         `json:"project_id"`
	Title                  string         `json:"title"`
	Lifecycle              string         `json:"lifecycle"`
	HeadRevision           int64          `json:"head_revision"`
	Version                int64          `json:"version"`
	FeedbackVersion        int64          `json:"feedback_version"`
	LegacyStatusUnverified sql.NullString `json:"legacy_status_unverified"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              time.Time      `json:"updated_at"`
}

type PlanAdoption struct {
	ID          string    `json:"id"`
	ProjectID   string    `json:"project_id"`
	ContainerID string    `json:"container_id"`
	Request     string    `json:"request"`
	Result      string    `json:"result"`
	Actor       string    `json:"actor"`
	SessionID   string    `json:"session_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type PlanComment struct {
	ID       string        `json:"id"`
	PlanID   string        `json:"plan_id"`
	Revision sql.NullInt64 `json:"revision"`
	Version  int64         `json:"version"`
	Body     string        `json:"body"`
}

type PlanCommentEvent struct {
	Actor     string    `json:"actor"`
	SessionID string    `json:"session_id"`
	CommentID string    `json:"comment_id"`
	Version   int64     `json:"version"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
}

type PlanDisposition struct {
	Actor          string    `json:"actor"`
	SessionID      string    `json:"session_id"`
	ID             string    `json:"id"`
	PlanID         string    `json:"plan_id"`
	TargetRevision int64     `json:"target_revision"`
	CommentID      string    `json:"comment_id"`
	CommentVersion int64     `json:"comment_version"`
	Disposition    string    `json:"disposition"`
	Reason         string    `json:"reason"`
	CreatedAt      time.Time `json:"created_at"`
}

type PlanIdempotency struct {
	ProjectID   string    `json:"project_id"`
	Scope       string    `json:"scope"`
	Key         string    `json:"key"`
	Fingerprint string    `json:"fingerprint"`
	Result      string    `json:"result"`
	CreatedAt   time.Time `json:"created_at"`
}

type PlanReviewEvent struct {
	Actor           string    `json:"actor"`
	SessionID       string    `json:"session_id"`
	ID              string    `json:"id"`
	PlanID          string    `json:"plan_id"`
	Revision        int64     `json:"revision"`
	Status          string    `json:"status"`
	ReviewVersion   int64     `json:"review_version"`
	FeedbackVersion int64     `json:"feedback_version"`
	DispositionIds  string    `json:"disposition_ids"`
	CreatedAt       time.Time `json:"created_at"`
}

type PlanRevision struct {
	PlanID        string    `json:"plan_id"`
	Revision      int64     `json:"revision"`
	ContentPath   string    `json:"content_path"`
	ContentSha256 string    `json:"content_sha256"`
	ContentBytes  int64     `json:"content_bytes"`
	SourceName    string    `json:"source_name"`
	ReviewStatus  string    `json:"review_status"`
	ReviewVersion int64     `json:"review_version"`
	CreatedAt     time.Time `json:"created_at"`
}

type Project struct {
	ID                   string         `json:"id"`
	Name                 string         `json:"name"`
	Description          sql.NullString `json:"description"`
	Prefix               string         `json:"prefix"`
	GovernanceGeneration int64          `json:"governance_generation"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

type Workspace struct {
	ID             string         `json:"id"`
	ProjectID      string         `json:"project_id"`
	Path           string         `json:"path"`
	Label          sql.NullString `json:"label"`
	Hostname       sql.NullString `json:"hostname"`
	GitRemote      sql.NullString `json:"git_remote"`
	PathType       string         `json:"path_type"`
	LastAccessedAt sql.NullTime   `json:"last_accessed_at"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}
