// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createPlan = `-- name: CreatePlan :exec
INSERT INTO legacy_plans (id, file_path, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type CreatePlanParams struct {
	ID        string    `json:"id"`
	FilePath  string    `json:"file_path"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) error {
	_, err := q.db.ExecContext(ctx, createPlan,
		arg.ID,
		arg.FilePath,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createPlanComment = `-- name: CreatePlanComment :exec
INSERT INTO legacy_plan_comments (
  id, plan_id, line_number, content, created_at,
  line_start, line_end, quoted_text, occurrence,
  heading_slug, context_before, context_after,
  updated_at, resolved_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePlanCommentParams struct {
	ID            string         `json:"id"`
	PlanID        string         `json:"plan_id"`
	LineNumber    sql.NullInt64  `json:"line_number"`
	Content       string         `json:"content"`
	CreatedAt     time.Time      `json:"created_at"`
	LineStart     sql.NullInt64  `json:"line_start"`
	LineEnd       sql.NullInt64  `json:"line_end"`
	QuotedText    sql.NullString `json:"quoted_text"`
	Occurrence    sql.NullInt64  `json:"occurrence"`
	HeadingSlug   sql.NullString `json:"heading_slug"`
	ContextBefore sql.NullString `json:"context_before"`
	ContextAfter  sql.NullString `json:"context_after"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	ResolvedAt    sql.NullTime   `json:"resolved_at"`
}

func (q *Queries) CreatePlanComment(ctx context.Context, arg CreatePlanCommentParams) error {
	_, err := q.db.ExecContext(ctx, createPlanComment,
		arg.ID,
		arg.PlanID,
		arg.LineNumber,
		arg.Content,
		arg.CreatedAt,
		arg.LineStart,
		arg.LineEnd,
		arg.QuotedText,
		arg.Occurrence,
		arg.HeadingSlug,
		arg.ContextBefore,
		arg.ContextAfter,
		arg.UpdatedAt,
		arg.ResolvedAt,
	)
	return err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM legacy_plans WHERE id = ?
`

func (q *Queries) DeletePlan(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePlan, id)
	return err
}

const deletePlanComment = `-- name: DeletePlanComment :exec
DELETE FROM legacy_plan_comments WHERE id = ?
`

func (q *Queries) DeletePlanComment(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePlanComment, id)
	return err
}

const getDurablePlan = `-- name: GetDurablePlan :one
SELECT id, project_id, title, lifecycle, head_revision, version, feedback_version, legacy_status_unverified, created_at, updated_at FROM plans WHERE project_id = ? AND id = ?
`

type GetDurablePlanParams struct {
	ProjectID string `json:"project_id"`
	ID        string `json:"id"`
}

func (q *Queries) GetDurablePlan(ctx context.Context, arg GetDurablePlanParams) (*Plan, error) {
	row := q.db.QueryRowContext(ctx, getDurablePlan, arg.ProjectID, arg.ID)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Lifecycle,
		&i.HeadRevision,
		&i.Version,
		&i.FeedbackVersion,
		&i.LegacyStatusUnverified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getPlan = `-- name: GetPlan :one
SELECT id, file_path, status, created_at, updated_at
FROM legacy_plans WHERE id = ?
`

func (q *Queries) GetPlan(ctx context.Context, id string) (*LegacyPlan, error) {
	row := q.db.QueryRowContext(ctx, getPlan, id)
	var i LegacyPlan
	err := row.Scan(
		&i.ID,
		&i.FilePath,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getPlanComment = `-- name: GetPlanComment :one
SELECT id, plan_id, line_number, content, created_at, line_start, line_end, quoted_text, occurrence, heading_slug, context_before, context_after, updated_at, resolved_at FROM legacy_plan_comments WHERE id = ?
`

func (q *Queries) GetPlanComment(ctx context.Context, id string) (*LegacyPlanComment, error) {
	row := q.db.QueryRowContext(ctx, getPlanComment, id)
	var i LegacyPlanComment
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.LineNumber,
		&i.Content,
		&i.CreatedAt,
		&i.LineStart,
		&i.LineEnd,
		&i.QuotedText,
		&i.Occurrence,
		&i.HeadingSlug,
		&i.ContextBefore,
		&i.ContextAfter,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return &i, err
}

const getPlanRevision = `-- name: GetPlanRevision :one
SELECT plan_id, revision, content_path, content_sha256, content_bytes, source_name, review_status, review_version, created_at FROM plan_revisions WHERE plan_id = ? AND revision = ?
`

type GetPlanRevisionParams struct {
	PlanID   string `json:"plan_id"`
	Revision int64  `json:"revision"`
}

func (q *Queries) GetPlanRevision(ctx context.Context, arg GetPlanRevisionParams) (*PlanRevision, error) {
	row := q.db.QueryRowContext(ctx, getPlanRevision, arg.PlanID, arg.Revision)
	var i PlanRevision
	err := row.Scan(
		&i.PlanID,
		&i.Revision,
		&i.ContentPath,
		&i.ContentSha256,
		&i.ContentBytes,
		&i.SourceName,
		&i.ReviewStatus,
		&i.ReviewVersion,
		&i.CreatedAt,
	)
	return &i, err
}

const listDurablePlans = `-- name: ListDurablePlans :many
SELECT id, project_id, title, lifecycle, head_revision, version, feedback_version, legacy_status_unverified, created_at, updated_at FROM plans WHERE project_id = ? AND lifecycle = ? ORDER BY created_at DESC, id LIMIT ? OFFSET ?
`

type ListDurablePlansParams struct {
	ProjectID string `json:"project_id"`
	Lifecycle string `json:"lifecycle"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

func (q *Queries) ListDurablePlans(ctx context.Context, arg ListDurablePlansParams) ([]*Plan, error) {
	rows, err := q.db.QueryContext(ctx, listDurablePlans,
		arg.ProjectID,
		arg.Lifecycle,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Lifecycle,
			&i.HeadRevision,
			&i.Version,
			&i.FeedbackVersion,
			&i.LegacyStatusUnverified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnedPlanIDs = `-- name: ListOwnedPlanIDs :many
SELECT id FROM plans WHERE project_id = ? ORDER BY id
`

func (q *Queries) ListOwnedPlanIDs(ctx context.Context, projectID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listOwnedPlanIDs, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanComments = `-- name: ListPlanComments :many
SELECT id, plan_id, line_number, content, created_at, line_start, line_end, quoted_text, occurrence, heading_slug, context_before, context_after, updated_at, resolved_at FROM legacy_plan_comments WHERE plan_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListPlanComments(ctx context.Context, planID string) ([]*LegacyPlanComment, error) {
	rows, err := q.db.QueryContext(ctx, listPlanComments, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*LegacyPlanComment{}
	for rows.Next() {
		var i LegacyPlanComment
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.LineNumber,
			&i.Content,
			&i.CreatedAt,
			&i.LineStart,
			&i.LineEnd,
			&i.QuotedText,
			&i.Occurrence,
			&i.HeadingSlug,
			&i.ContextBefore,
			&i.ContextAfter,
			&i.UpdatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanRevisions = `-- name: ListPlanRevisions :many
SELECT plan_id, revision, content_path, content_sha256, content_bytes, source_name, review_status, review_version, created_at FROM plan_revisions WHERE plan_id = ? ORDER BY revision DESC LIMIT ? OFFSET ?
`

type ListPlanRevisionsParams struct {
	PlanID string `json:"plan_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListPlanRevisions(ctx context.Context, arg ListPlanRevisionsParams) ([]*PlanRevision, error) {
	rows, err := q.db.QueryContext(ctx, listPlanRevisions, arg.PlanID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*PlanRevision{}
	for rows.Next() {
		var i PlanRevision
		if err := rows.Scan(
			&i.PlanID,
			&i.Revision,
			&i.ContentPath,
			&i.ContentSha256,
			&i.ContentBytes,
			&i.SourceName,
			&i.ReviewStatus,
			&i.ReviewVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlanComment = `-- name: UpdatePlanComment :exec
UPDATE legacy_plan_comments
SET content = ?, line_number = ?,
    line_start = ?, line_end = ?, quoted_text = ?, occurrence = ?,
    heading_slug = ?, context_before = ?, context_after = ?,
    updated_at = ?, resolved_at = ?
WHERE id = ?
`

type UpdatePlanCommentParams struct {
	Content       string         `json:"content"`
	LineNumber    sql.NullInt64  `json:"line_number"`
	LineStart     sql.NullInt64  `json:"line_start"`
	LineEnd       sql.NullInt64  `json:"line_end"`
	QuotedText    sql.NullString `json:"quoted_text"`
	Occurrence    sql.NullInt64  `json:"occurrence"`
	HeadingSlug   sql.NullString `json:"heading_slug"`
	ContextBefore sql.NullString `json:"context_before"`
	ContextAfter  sql.NullString `json:"context_after"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	ResolvedAt    sql.NullTime   `json:"resolved_at"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdatePlanComment(ctx context.Context, arg UpdatePlanCommentParams) error {
	_, err := q.db.ExecContext(ctx, updatePlanComment,
		arg.Content,
		arg.LineNumber,
		arg.LineStart,
		arg.LineEnd,
		arg.QuotedText,
		arg.Occurrence,
		arg.HeadingSlug,
		arg.ContextBefore,
		arg.ContextAfter,
		arg.UpdatedAt,
		arg.ResolvedAt,
		arg.ID,
	)
	return err
}

const updatePlanStatus = `-- name: UpdatePlanStatus :exec
UPDATE legacy_plans SET status = ?, updated_at = ? WHERE id = ?
`

type UpdatePlanStatusParams struct {
	Status    string    `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdatePlanStatus(ctx context.Context, arg UpdatePlanStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePlanStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
