// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countPlansByStatus = `-- name: CountPlansByStatus :one
SELECT COUNT(*) as count FROM plans WHERE project_id = ? AND status = ?
`

type CountPlansByStatusParams struct {
	ProjectID string `json:"project_id"`
	Status    string `json:"status"`
}

func (q *Queries) CountPlansByStatus(ctx context.Context, arg CountPlansByStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlansByStatus, arg.ProjectID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (id, project_id, issue_id, title, content, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, title, content, status, issue_id, created_at, updated_at
`

type CreatePlanParams struct {
	ID        string         `json:"id"`
	ProjectID string         `json:"project_id"`
	IssueID   sql.NullString `json:"issue_id"`
	Title     string         `json:"title"`
	Content   string         `json:"content"`
	Status    string         `json:"status"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (*Plan, error) {
	row := q.db.QueryRowContext(ctx, createPlan,
		arg.ID,
		arg.ProjectID,
		arg.IssueID,
		arg.Title,
		arg.Content,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.IssueID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans WHERE id = ?
`

func (q *Queries) DeletePlan(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePlan, id)
	return err
}

const getPlan = `-- name: GetPlan :one
SELECT id, project_id, title, content, status, issue_id, created_at, updated_at FROM plans WHERE id = ?
`

func (q *Queries) GetPlan(ctx context.Context, id string) (*Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.IssueID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getPlanByIssueID = `-- name: GetPlanByIssueID :one
SELECT id, project_id, title, content, status, issue_id, created_at, updated_at FROM plans WHERE issue_id = ?
`

func (q *Queries) GetPlanByIssueID(ctx context.Context, issueID sql.NullString) (*Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlanByIssueID, issueID)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.IssueID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listPlans = `-- name: ListPlans :many
SELECT id, project_id, title, content, status, issue_id, created_at, updated_at FROM plans
WHERE project_id = ? AND (? = '' OR status = ?)
ORDER BY updated_at DESC
`

type ListPlansParams struct {
	ProjectID string      `json:"project_id"`
	Column2   interface{} `json:"column_2"`
	Status    string      `json:"status"`
}

func (q *Queries) ListPlans(ctx context.Context, arg ListPlansParams) ([]*Plan, error) {
	rows, err := q.db.QueryContext(ctx, listPlans, arg.ProjectID, arg.Column2, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.IssueID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlanContent = `-- name: UpdatePlanContent :exec
UPDATE plans SET title = ?, content = ?, updated_at = ? WHERE id = ?
`

type UpdatePlanContentParams struct {
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdatePlanContent(ctx context.Context, arg UpdatePlanContentParams) error {
	_, err := q.db.ExecContext(ctx, updatePlanContent,
		arg.Title,
		arg.Content,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updatePlanStatus = `-- name: UpdatePlanStatus :exec
UPDATE plans SET status = ?, updated_at = ? WHERE id = ?
`

type UpdatePlanStatusParams struct {
	Status    string    `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdatePlanStatus(ctx context.Context, arg UpdatePlanStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePlanStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const upsertPlan = `-- name: UpsertPlan :one
INSERT INTO plans (id, project_id, issue_id, title, content, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (issue_id) DO UPDATE SET
    title = excluded.title,
    content = excluded.content,
    updated_at = excluded.updated_at
RETURNING id, project_id, title, content, status, issue_id, created_at, updated_at
`

type UpsertPlanParams struct {
	ID        string         `json:"id"`
	ProjectID string         `json:"project_id"`
	IssueID   sql.NullString `json:"issue_id"`
	Title     string         `json:"title"`
	Content   string         `json:"content"`
	Status    string         `json:"status"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) UpsertPlan(ctx context.Context, arg UpsertPlanParams) (*Plan, error) {
	row := q.db.QueryRowContext(ctx, upsertPlan,
		arg.ID,
		arg.ProjectID,
		arg.IssueID,
		arg.Title,
		arg.Content,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.IssueID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
