// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package db

import (
	"context"
	"time"
)

const countPlanLinks = `-- name: CountPlanLinks :one
SELECT COUNT(*) as count FROM issue_plans WHERE plan_id = ?
`

func (q *Queries) CountPlanLinks(ctx context.Context, planID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlanLinks, planID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (id, workspace_id, title, content, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, workspace_id, title, content, created_at, updated_at
`

type CreatePlanParams struct {
	ID          string    `json:"id"`
	WorkspaceID string    `json:"workspace_id"`
	Title       string    `json:"title"`
	Content     string    `json:"content"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (*Plan, error) {
	row := q.db.QueryRowContext(ctx, createPlan,
		arg.ID,
		arg.WorkspaceID,
		arg.Title,
		arg.Content,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans WHERE id = ?
`

func (q *Queries) DeletePlan(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePlan, id)
	return err
}

const getLinkedIssues = `-- name: GetLinkedIssues :many
SELECT issue_id FROM issue_plans WHERE plan_id = ?
`

func (q *Queries) GetLinkedIssues(ctx context.Context, planID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getLinkedIssues, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var issue_id string
		if err := rows.Scan(&issue_id); err != nil {
			return nil, err
		}
		items = append(items, issue_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkedPlans = `-- name: GetLinkedPlans :many
SELECT p.id, p.workspace_id, p.title, p.content, p.created_at, p.updated_at FROM plans p
INNER JOIN issue_plans ip ON ip.plan_id = p.id
WHERE ip.issue_id = ?
ORDER BY p.updated_at DESC
`

func (q *Queries) GetLinkedPlans(ctx context.Context, issueID string) ([]*Plan, error) {
	rows, err := q.db.QueryContext(ctx, getLinkedPlans, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlan = `-- name: GetPlan :one
SELECT id, workspace_id, title, content, created_at, updated_at FROM plans WHERE id = ?
`

func (q *Queries) GetPlan(ctx context.Context, id string) (*Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const linkIssueToPlan = `-- name: LinkIssueToPlan :exec
INSERT INTO issue_plans (issue_id, plan_id, created_at)
VALUES (?, ?, ?)
ON CONFLICT (issue_id, plan_id) DO NOTHING
`

type LinkIssueToPlanParams struct {
	IssueID   string    `json:"issue_id"`
	PlanID    string    `json:"plan_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) LinkIssueToPlan(ctx context.Context, arg LinkIssueToPlanParams) error {
	_, err := q.db.ExecContext(ctx, linkIssueToPlan, arg.IssueID, arg.PlanID, arg.CreatedAt)
	return err
}

const listPlans = `-- name: ListPlans :many
SELECT id, workspace_id, title, content, created_at, updated_at FROM plans
WHERE workspace_id = ?
ORDER BY updated_at DESC
`

func (q *Queries) ListPlans(ctx context.Context, workspaceID string) ([]*Plan, error) {
	rows, err := q.db.QueryContext(ctx, listPlans, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkIssueFromPlan = `-- name: UnlinkIssueFromPlan :exec
DELETE FROM issue_plans WHERE issue_id = ? AND plan_id = ?
`

type UnlinkIssueFromPlanParams struct {
	IssueID string `json:"issue_id"`
	PlanID  string `json:"plan_id"`
}

func (q *Queries) UnlinkIssueFromPlan(ctx context.Context, arg UnlinkIssueFromPlanParams) error {
	_, err := q.db.ExecContext(ctx, unlinkIssueFromPlan, arg.IssueID, arg.PlanID)
	return err
}

const updatePlan = `-- name: UpdatePlan :exec
UPDATE plans SET title = ?, content = ?, updated_at = ?
WHERE id = ?
`

type UpdatePlanParams struct {
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) error {
	_, err := q.db.ExecContext(ctx, updatePlan,
		arg.Title,
		arg.Content,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
