// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countProjectsByID = `-- name: CountProjectsByID :one
SELECT COUNT(*) as count FROM projects WHERE id = ?
`

func (q *Queries) CountProjectsByID(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectsByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjectsByName = `-- name: CountProjectsByName :one
SELECT COUNT(*) as count FROM projects WHERE name = ?
`

func (q *Queries) CountProjectsByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectsByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (id, name, description, prefix, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateProjectParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Prefix      string         `json:"prefix"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Prefix,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteConfigByProject = `-- name: DeleteConfigByProject :exec
DELETE FROM config WHERE project_id = ?
`

func (q *Queries) DeleteConfigByProject(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, deleteConfigByProject, projectID)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, description, prefix, created_at, updated_at FROM projects WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id string) (*Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Prefix,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT id, name, description, prefix, created_at, updated_at FROM projects WHERE name = ?
`

func (q *Queries) GetProjectByName(ctx context.Context, name string) (*Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByName, name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Prefix,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, description, prefix, created_at, updated_at FROM projects ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context) ([]*Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Prefix,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveIssuesToProject = `-- name: MoveIssuesToProject :execresult
UPDATE issues SET project_id = ? WHERE project_id = ?
`

type MoveIssuesToProjectParams struct {
	ProjectID   string `json:"project_id"`
	ProjectID_2 string `json:"project_id_2"`
}

func (q *Queries) MoveIssuesToProject(ctx context.Context, arg MoveIssuesToProjectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, moveIssuesToProject, arg.ProjectID, arg.ProjectID_2)
}

const movePlansToProject = `-- name: MovePlansToProject :execresult
UPDATE plans SET project_id = ? WHERE project_id = ?
`

type MovePlansToProjectParams struct {
	ProjectID   string `json:"project_id"`
	ProjectID_2 string `json:"project_id_2"`
}

func (q *Queries) MovePlansToProject(ctx context.Context, arg MovePlansToProjectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, movePlansToProject, arg.ProjectID, arg.ProjectID_2)
}

const updateProject = `-- name: UpdateProject :exec
UPDATE projects
SET name = ?, description = ?, updated_at = ?
WHERE id = ?
`

type UpdateProjectParams struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	UpdatedAt   time.Time      `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.ExecContext(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
