// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shares.sql

package db

import (
	"context"
	"database/sql"
)

const deleteShare = `-- name: DeleteShare :exec
DELETE FROM shares WHERE id = ?
`

func (q *Queries) DeleteShare(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteShare, id)
	return err
}

const getShare = `-- name: GetShare :one
SELECT id, kind, url, key_b64url, edit_token, plan_file, created_at FROM shares WHERE id = ?
`

func (q *Queries) GetShare(ctx context.Context, id string) (*Share, error) {
	row := q.db.QueryRowContext(ctx, getShare, id)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Url,
		&i.KeyB64url,
		&i.EditToken,
		&i.PlanFile,
		&i.CreatedAt,
	)
	return &i, err
}

const listShares = `-- name: ListShares :many
SELECT id, kind, url, key_b64url, edit_token, plan_file, created_at FROM shares ORDER BY created_at DESC
`

func (q *Queries) ListShares(ctx context.Context) ([]*Share, error) {
	rows, err := q.db.QueryContext(ctx, listShares)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Share{}
	for rows.Next() {
		var i Share
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Url,
			&i.KeyB64url,
			&i.EditToken,
			&i.PlanFile,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertShare = `-- name: UpsertShare :exec
INSERT INTO shares (id, kind, url, key_b64url, edit_token, plan_file, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    kind       = excluded.kind,
    url        = excluded.url,
    key_b64url = excluded.key_b64url,
    edit_token = excluded.edit_token,
    plan_file  = excluded.plan_file,
    created_at = excluded.created_at
`

type UpsertShareParams struct {
	ID        string         `json:"id"`
	Kind      string         `json:"kind"`
	Url       string         `json:"url"`
	KeyB64url string         `json:"key_b64url"`
	EditToken string         `json:"edit_token"`
	PlanFile  sql.NullString `json:"plan_file"`
	CreatedAt string         `json:"created_at"`
}

func (q *Queries) UpsertShare(ctx context.Context, arg UpsertShareParams) error {
	_, err := q.db.ExecContext(ctx, upsertShare,
		arg.ID,
		arg.Kind,
		arg.Url,
		arg.KeyB64url,
		arg.EditToken,
		arg.PlanFile,
		arg.CreatedAt,
	)
	return err
}
