// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package db

import (
	"context"
	"database/sql"
)

const getAverageLeadTime = `-- name: GetAverageLeadTime :one
SELECT AVG(
    (julianday(closed_at) - julianday(created_at)) * 24
) as avg_lead_time_hours
FROM issues
WHERE workspace_id = ?
  AND status = 'closed'
  AND closed_at IS NOT NULL
`

func (q *Queries) GetAverageLeadTime(ctx context.Context, workspaceID string) (sql.NullFloat64, error) {
	row := q.db.QueryRowContext(ctx, getAverageLeadTime, workspaceID)
	var avg_lead_time_hours sql.NullFloat64
	err := row.Scan(&avg_lead_time_hours)
	return avg_lead_time_hours, err
}

const getReadyIssueCount = `-- name: GetReadyIssueCount :one
SELECT COUNT(*) as count FROM issues i
WHERE i.workspace_id = ?
  AND i.status IN ('open', 'in_progress')
  AND NOT EXISTS (
    SELECT 1 FROM dependencies d
    JOIN issues blocker ON d.depends_on_id = blocker.id
    WHERE d.issue_id = i.id
      AND d.type IN ('blocks', 'parent-child')
      AND blocker.status != 'closed'
  )
`

func (q *Queries) GetReadyIssueCount(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getReadyIssueCount, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWorkspaceStats = `-- name: GetWorkspaceStats :one
SELECT
    workspace_id,
    COUNT(*) as total_issues,
    SUM(CASE WHEN status = 'open' THEN 1 ELSE 0 END) as open_issues,
    SUM(CASE WHEN status = 'in_progress' THEN 1 ELSE 0 END) as in_progress_issues,
    SUM(CASE WHEN status = 'closed' THEN 1 ELSE 0 END) as closed_issues,
    SUM(CASE WHEN status = 'blocked' THEN 1 ELSE 0 END) as blocked_issues,
    SUM(CASE WHEN status = 'deferred' THEN 1 ELSE 0 END) as deferred_issues
FROM issues
WHERE workspace_id = ?
GROUP BY workspace_id
`

type GetWorkspaceStatsRow struct {
	WorkspaceID      string          `json:"workspace_id"`
	TotalIssues      int64           `json:"total_issues"`
	OpenIssues       sql.NullFloat64 `json:"open_issues"`
	InProgressIssues sql.NullFloat64 `json:"in_progress_issues"`
	ClosedIssues     sql.NullFloat64 `json:"closed_issues"`
	BlockedIssues    sql.NullFloat64 `json:"blocked_issues"`
	DeferredIssues   sql.NullFloat64 `json:"deferred_issues"`
}

func (q *Queries) GetWorkspaceStats(ctx context.Context, workspaceID string) (*GetWorkspaceStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceStats, workspaceID)
	var i GetWorkspaceStatsRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.TotalIssues,
		&i.OpenIssues,
		&i.InProgressIssues,
		&i.ClosedIssues,
		&i.BlockedIssues,
		&i.DeferredIssues,
	)
	return &i, err
}
