// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_paths.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createWorkspacePath = `-- name: CreateWorkspacePath :exec
INSERT INTO workspace_paths (id, workspace_id, path, label, hostname, git_remote, path_type, last_accessed_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateWorkspacePathParams struct {
	ID             string         `json:"id"`
	WorkspaceID    string         `json:"workspace_id"`
	Path           string         `json:"path"`
	Label          sql.NullString `json:"label"`
	Hostname       sql.NullString `json:"hostname"`
	GitRemote      sql.NullString `json:"git_remote"`
	PathType       string         `json:"path_type"`
	LastAccessedAt sql.NullTime   `json:"last_accessed_at"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

func (q *Queries) CreateWorkspacePath(ctx context.Context, arg CreateWorkspacePathParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspacePath,
		arg.ID,
		arg.WorkspaceID,
		arg.Path,
		arg.Label,
		arg.Hostname,
		arg.GitRemote,
		arg.PathType,
		arg.LastAccessedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteWorkspacePath = `-- name: DeleteWorkspacePath :exec
DELETE FROM workspace_paths WHERE id = ?
`

func (q *Queries) DeleteWorkspacePath(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspacePath, id)
	return err
}

const deleteWorkspacePathsByWorkspace = `-- name: DeleteWorkspacePathsByWorkspace :exec
DELETE FROM workspace_paths WHERE workspace_id = ?
`

func (q *Queries) DeleteWorkspacePathsByWorkspace(ctx context.Context, workspaceID string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspacePathsByWorkspace, workspaceID)
	return err
}

const getWorkspacePath = `-- name: GetWorkspacePath :one
SELECT id, workspace_id, path, label, hostname, git_remote, path_type, last_accessed_at, created_at, updated_at FROM workspace_paths WHERE id = ?
`

func (q *Queries) GetWorkspacePath(ctx context.Context, id string) (*WorkspacePath, error) {
	row := q.db.QueryRowContext(ctx, getWorkspacePath, id)
	var i WorkspacePath
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Path,
		&i.Label,
		&i.Hostname,
		&i.GitRemote,
		&i.PathType,
		&i.LastAccessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listAllWorkspacePaths = `-- name: ListAllWorkspacePaths :many
SELECT id, workspace_id, path, label, hostname, git_remote, path_type, last_accessed_at, created_at, updated_at FROM workspace_paths ORDER BY workspace_id, path
`

func (q *Queries) ListAllWorkspacePaths(ctx context.Context) ([]*WorkspacePath, error) {
	rows, err := q.db.QueryContext(ctx, listAllWorkspacePaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*WorkspacePath{}
	for rows.Next() {
		var i WorkspacePath
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Path,
			&i.Label,
			&i.Hostname,
			&i.GitRemote,
			&i.PathType,
			&i.LastAccessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacePaths = `-- name: ListWorkspacePaths :many
SELECT id, workspace_id, path, label, hostname, git_remote, path_type, last_accessed_at, created_at, updated_at FROM workspace_paths WHERE workspace_id = ? ORDER BY path
`

func (q *Queries) ListWorkspacePaths(ctx context.Context, workspaceID string) ([]*WorkspacePath, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspacePaths, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*WorkspacePath{}
	for rows.Next() {
		var i WorkspacePath
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Path,
			&i.Label,
			&i.Hostname,
			&i.GitRemote,
			&i.PathType,
			&i.LastAccessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveWorkspaceByPath = `-- name: ResolveWorkspaceByPath :one
SELECT id, workspace_id, path, label, hostname, git_remote, path_type, last_accessed_at, created_at, updated_at FROM workspace_paths WHERE path = ?
`

func (q *Queries) ResolveWorkspaceByPath(ctx context.Context, path string) (*WorkspacePath, error) {
	row := q.db.QueryRowContext(ctx, resolveWorkspaceByPath, path)
	var i WorkspacePath
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Path,
		&i.Label,
		&i.Hostname,
		&i.GitRemote,
		&i.PathType,
		&i.LastAccessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updatePathLastAccessed = `-- name: UpdatePathLastAccessed :exec
UPDATE workspace_paths SET last_accessed_at = ?, updated_at = ? WHERE id = ?
`

type UpdatePathLastAccessedParams struct {
	LastAccessedAt sql.NullTime `json:"last_accessed_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	ID             string       `json:"id"`
}

func (q *Queries) UpdatePathLastAccessed(ctx context.Context, arg UpdatePathLastAccessedParams) error {
	_, err := q.db.ExecContext(ctx, updatePathLastAccessed, arg.LastAccessedAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateWorkspacePath = `-- name: UpdateWorkspacePath :exec
UPDATE workspace_paths SET label = ?, hostname = ?, git_remote = ?, path_type = ?, updated_at = ? WHERE id = ?
`

type UpdateWorkspacePathParams struct {
	Label     sql.NullString `json:"label"`
	Hostname  sql.NullString `json:"hostname"`
	GitRemote sql.NullString `json:"git_remote"`
	PathType  string         `json:"path_type"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateWorkspacePath(ctx context.Context, arg UpdateWorkspacePathParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspacePath,
		arg.Label,
		arg.Hostname,
		arg.GitRemote,
		arg.PathType,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
