// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createWorkspace = `-- name: CreateWorkspace :exec
INSERT INTO workspaces (id, project_id, path, label, hostname, git_remote, path_type, last_accessed_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateWorkspaceParams struct {
	ID             string         `json:"id"`
	ProjectID      string         `json:"project_id"`
	Path           string         `json:"path"`
	Label          sql.NullString `json:"label"`
	Hostname       sql.NullString `json:"hostname"`
	GitRemote      sql.NullString `json:"git_remote"`
	PathType       string         `json:"path_type"`
	LastAccessedAt sql.NullTime   `json:"last_accessed_at"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspace,
		arg.ID,
		arg.ProjectID,
		arg.Path,
		arg.Label,
		arg.Hostname,
		arg.GitRemote,
		arg.PathType,
		arg.LastAccessedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE id = ?
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspace, id)
	return err
}

const deleteWorkspacesByProject = `-- name: DeleteWorkspacesByProject :exec
DELETE FROM workspaces WHERE project_id = ?
`

func (q *Queries) DeleteWorkspacesByProject(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspacesByProject, projectID)
	return err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, project_id, path, label, hostname, git_remote, path_type, last_accessed_at, created_at, updated_at FROM workspaces WHERE id = ?
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (*Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Path,
		&i.Label,
		&i.Hostname,
		&i.GitRemote,
		&i.PathType,
		&i.LastAccessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listAllWorkspaces = `-- name: ListAllWorkspaces :many
SELECT id, project_id, path, label, hostname, git_remote, path_type, last_accessed_at, created_at, updated_at FROM workspaces ORDER BY project_id, path
`

func (q *Queries) ListAllWorkspaces(ctx context.Context) ([]*Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listAllWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Path,
			&i.Label,
			&i.Hostname,
			&i.GitRemote,
			&i.PathType,
			&i.LastAccessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, project_id, path, label, hostname, git_remote, path_type, last_accessed_at, created_at, updated_at FROM workspaces WHERE project_id = ? ORDER BY path
`

func (q *Queries) ListWorkspaces(ctx context.Context, projectID string) ([]*Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Path,
			&i.Label,
			&i.Hostname,
			&i.GitRemote,
			&i.PathType,
			&i.LastAccessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspace = `-- name: UpdateWorkspace :exec
UPDATE workspaces SET label = ?, hostname = ?, git_remote = ?, path_type = ?, updated_at = ? WHERE id = ?
`

type UpdateWorkspaceParams struct {
	Label     sql.NullString `json:"label"`
	Hostname  sql.NullString `json:"hostname"`
	GitRemote sql.NullString `json:"git_remote"`
	PathType  string         `json:"path_type"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspace,
		arg.Label,
		arg.Hostname,
		arg.GitRemote,
		arg.PathType,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateWorkspaceLastAccessed = `-- name: UpdateWorkspaceLastAccessed :exec
UPDATE workspaces SET last_accessed_at = ?, updated_at = ? WHERE id = ?
`

type UpdateWorkspaceLastAccessedParams struct {
	LastAccessedAt sql.NullTime `json:"last_accessed_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
	ID             string       `json:"id"`
}

func (q *Queries) UpdateWorkspaceLastAccessed(ctx context.Context, arg UpdateWorkspaceLastAccessedParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspaceLastAccessed, arg.LastAccessedAt, arg.UpdatedAt, arg.ID)
	return err
}
