// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const countWorkspacesByID = `-- name: CountWorkspacesByID :one
SELECT COUNT(*) as count FROM workspaces WHERE id = ?
`

func (q *Queries) CountWorkspacesByID(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkspacesByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkspacesByName = `-- name: CountWorkspacesByName :one
SELECT COUNT(*) as count FROM workspaces WHERE name = ?
`

func (q *Queries) CountWorkspacesByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkspacesByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkspace = `-- name: CreateWorkspace :exec
INSERT INTO workspaces (id, name, path, description, prefix, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateWorkspaceParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Path        sql.NullString `json:"path"`
	Description sql.NullString `json:"description"`
	Prefix      string         `json:"prefix"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspace,
		arg.ID,
		arg.Name,
		arg.Path,
		arg.Description,
		arg.Prefix,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE id = ?
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspace, id)
	return err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, path, description, prefix, created_at, updated_at FROM workspaces WHERE id = ?
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (*Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Description,
		&i.Prefix,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getWorkspaceByName = `-- name: GetWorkspaceByName :one
SELECT id, name, path, description, prefix, created_at, updated_at FROM workspaces WHERE name = ?
`

func (q *Queries) GetWorkspaceByName(ctx context.Context, name string) (*Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByName, name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Description,
		&i.Prefix,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getWorkspaceByPath = `-- name: GetWorkspaceByPath :one
SELECT id, name, path, description, prefix, created_at, updated_at FROM workspaces WHERE path = ?
`

func (q *Queries) GetWorkspaceByPath(ctx context.Context, path sql.NullString) (*Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceByPath, path)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Description,
		&i.Prefix,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listWorkspaces = `-- name: ListWorkspaces :many
SELECT id, name, path, description, prefix, created_at, updated_at FROM workspaces ORDER BY name
`

func (q *Queries) ListWorkspaces(ctx context.Context) ([]*Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.Description,
			&i.Prefix,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspace = `-- name: UpdateWorkspace :exec
UPDATE workspaces
SET name = ?, path = ?, description = ?, updated_at = ?
WHERE id = ?
`

type UpdateWorkspaceParams struct {
	Name        string         `json:"name"`
	Path        sql.NullString `json:"path"`
	Description sql.NullString `json:"description"`
	UpdatedAt   time.Time      `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkspace,
		arg.Name,
		arg.Path,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
